### ISSUE TITLE
Rework how we do changelog updates

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#1032]
We maintain one changelog per crate. The purpose of these changelogs is to make it easy for downstream developers to figure out what they need to do or handle in order to update their dependencies.

These changelogs are effectively global variables, and PRs currently need to write to them in order to serialize their state. This leads to conflicts between PRs that happen to overlap, as well as with PRs that clean up the changelogs for usability (e.g. #1030).

We should figure out and document a process for collecting changelog updates that doesn't conflict as readily, but still ensures that we capture all the information we need for crafting good changelogs at release time.

**Comment by str4d** [comment]
The overall structure of our changelogs comes from [Keep a Changelog](https://keepachangelog.com/en/1.1.0/). The style of changelog I (@str4d) aim for is:
- Nested: grouping changes by common module paths (which reflect common functional areas within the crate).
- Clean: avoiding duplicative content where possible that gets in the way of figuring out what structs or methods are affected.
  - This can require grouping by the same common module paths in more than one place, creating duplication there, but that duplication is more regular and more easily parsed by the eye IME.
- User-focused: changelog entries are written to be read by the downstream crate users, not the crate developers.
  - Module paths include the crate name, as the downstream user would see them.
  - Focus on the things that standard tooling won't necessarily help with.
    - When adding a struct variant to an enum, we just list the name of the new variant, not all its fields (which the compiler will help them with).
    - When documenting type-constrained impls (e.g. `Bundle::<InProgress<_, Unsigned>>::prepare`), we don't include the `InProgressProofs` bound on `_` (because the `InProgress` struct requires it and the compiler will enforce it), but we do include the `Unsigned` (without which the method is unavailable).
  - Changes that don't affect the "public API" are omitted.

I'm probably forgetting some things; I'll update the above if I remember them. In any case, whatever changelog process we arrive at will likely require a human pass prior to releases, because automated tooling generally doesn't produce a description of the delta that satisfies the above.

**Comment by str4d** [comment]
We might be able to leverage something like https://crates.io/crates/cargo-semver-checks for detecting changes to the public API that need to be included in the changelog.

**Comment by str4d** [comment]
One way we could de-conflict changelog updates, is for PRs to store their changelog updates outside of the global changelogs, and then before releases we pull those updates together into a cohesive changelog. @nuttycom suggested storing them in the commit messages, using #1003 as an example: https://github.com/nuttycom/librustzcash/commit/518fb437b5949d91b71cbef733e756c68b17f23c

**Comment by daira** [comment]
I suggest putting them in the initial comment of a PR. That way they will never conflict, but will still be easy to find either on GitHub or in merge commit messages. It'll also be easy to see them in PR reviews.

**Comment by nuttycom** [comment]
> I suggest putting them in the initial comment of a PR. That way they will never conflict, but will still be easy to find either on GitHub or in merge commit messages. It'll also be easy to see them in PR reviews.

This seems challenging, because you don't know what's going to be in subsequent commits, or how many there will be, when you start working on something?

**Comment by daira** [comment]
The initial comment is editable.

**Comment by nuttycom** [comment]
Looking at #1003 and #891 being done using the "Put the changelog in the commit message, then aggregate later" approach, my feeling at the moment is that the way that we've historically done this, just updating the changelog as we go along, is probably better; I was a bit frustrated by #1030 in that it caused massive conflicts with in-flight PRs. But I think that the solution there is just to not do major changelog cleanups outside of the release process; none of this would have been an issue had it not been for the desire to do that cleanup. Cleaning up the changelog is a fine and good thing to do, but let's only do it when it's not going to cause as many issues.

**Comment by str4d** [comment]
> none of this would have been an issue had it not been for the desire to do that cleanup. Cleaning up the changelog is a fine and good thing to do, but let's only do it when it's not going to cause as many issues.

I did think it wasn't going to cause many issues, because I thought we were at a lull point. My suspicion is that _any_ point will cause issues, even right at a release, because there will always be some or other WIP PR on the go that conflicts. So the question is what the threshold is for "many issues", and how we even detect that.

I also said that I was happy to take the route of "rebase the cleanup PR as we go", which is the alternative: leave cleanup-related conflicts to the cleanup PR. Yes that likely requires more conflict-resolution work overall (you still have conflict resolution with the individual PRs, and then also with the cleanup PR), but that seems fine to me because it's functionally equivalent to "discard the mid-point cleanup PR and redo it at release time", except that you get the benefit of already having done one cleanup so you know roughly how the second one will go.

**Comment by str4d** [comment]
I've rebased #1033 and reverted it to directly editing the changelogs instead of storing change entries in the commit messages. I'll continue doing things the old way until we decide on an approach for this issue (or close it).

**Comment by nuttycom** [comment]
Closing as "we're going to keep doing what we've been doing."
