### ISSUE TITLE
zcash_client_sqlite: Identify shielding transactions in the output of the v_transactions view.

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#1046]
The specific ask here is to identify transactions that were created as a result of clicking the "shield funds" button in a wallet (i.e. by calling `propose_shielding`). These transactions have the following characteristics:
- Only transparent inputs.
- Only shielded outputs.
- Inputs are all from the wallet.
- Outputs are all to the wallet.
  - i.e. this is a wallet-internal transaction, though for historic wallets the outputs might not have been sent to wallet-internal addresses.

**Comment by str4d** [comment]
We can't implement exactly the above in `v_transactions`:
- We do not record any details about other inputs beyond what we ourselves have spent.
- We do record details about other outputs in the `sent_notes` table, but probably not as reliably as we'd need.

However, we _can_ implement the following check:
- Only transparent inputs from our wallet.
- Only shielded outputs to our wallet.

This can be done by adding a count of `does_not_match_shielding` that we increment when we observe a spent note that is not from the transparent pool, or a received note that is to the transparent pool. Then sum that counter and `is_shielding` is when the counter is zero.
