### ISSUE TITLE
Transparent input details should be retrieved with transactions on account recovery

### ISSUE THREAD

**Issue by AArnott** [zcash/librustzcash#1074]
When downloading a transaction that includes transparent inputs, the details of the transparent inputs must be downloaded as well so that the transaction amounts and fees can be correctly calculated. 

See brief [discussion on discord](https://discord.com/channels/809218587167293450/972649509651906711/1187261876904656926).

Note this is not just for account recovery scenarios. It could be that the account is already fully downloaded, but another instance of that same account exists on another app or device and the transaction was created there, so really any time the transaction is downloaded rather than created locally, these details should download.

**Comment by AArnott** [comment]
This is necessary for reliably computing fees, as @nuttycom described in [this discord conversation](https://discord.com/channels/809218587167293450/972649509651906711/1187125009068597268).

**Comment by nuttycom** [comment]
Related to #1361

**Comment by AArnott** [comment]
Incidentally, I've implemented this myself in the sync code I built on top of librustzcash. Let me know if you're interested.

**Comment by nuttycom** [comment]
Fixed in #1473
