### ISSUE TITLE
Decide on the policy for which pool change goes to when creating a transaction

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#1163]
Suggested policy for `zcash_client_backend`, when there is change:

1. If the transaction would already have Orchard components, send change to Orchard.
   * This implies that Orchard must be feature-flagged on.
2. Else if the transaction would already have Sapling components, send change to Sapling.
   * This implies that Sapling must be feature-flagged on.
3. Else if Orchard is feature-flagged on, send change to Orchard.
4. Else if Sapling is feature-flagged on, send change to Sapling.
5. Else (compile-time or run-time) error.

This prefers Orchard but tries to avoid revealing the change amount for an otherwise all-Sapling tx.

We don't support the case where neither Orchard nor Sapling are feature-flagged on, because there are already pervasive assumptions that we are always able to send to a shielded pool.

**Comment by str4d** [comment]
We decided on this, and deferred other ideas for improvements (e.g. #1222).
