### ISSUE TITLE
zcash_client_backend: Add crate-level documentation of how accounts work.

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#1209]
> Congratulations on threading the needle of addressing my review comment while managing to avoid writing the more extensive documentation I wanted 😄 (please open an issue for writing crate-level documentation about how accounts work in `zcash_client_backend`).

_Originally posted by @str4d in https://github.com/zcash/librustzcash/pull/1202#discussion_r1508034685_

**Comment by str4d** [comment]
The comment in question:
> "unique account identifiers" is not clear, particularly to existing downstream users of zcash_client_backend (but not necessarily zcash_client_sqlite) who are familiar with the BIP 44 / ZIP 32 semantics for "account identifier" that this crate has previously consistently used.
>
> Expand this documentation to explain that this is the type used by the wallet to internally track "accounts", and explain (either here, or in the WalletRead trait documentation, or maybe in crate-level documentation) what an "account" is, what it means within the wallet's overall data model, and how it maps to (or can be mapped to) the BIP 44 / ZIP 32 semantics.
