### ISSUE TITLE
v_tx_outputs `from_account_id` column left NULL for notes sent to self

### ISSUE THREAD

**Issue by AArnott** [zcash/librustzcash#1304]
This issue screws up running balance calculations in my app, by interfering with the ability to detect 'change' line items in a transaction.  I expect change rows in `v_tx_outputs` to have `from_account_id` and `to_account_id` set to the same value, but instead, `from_account_id` is set to NULL, suggesting that all change is novel _income_ for the account, causing running balance to skyrocket.

I believe this is a recent regression in librustzcash because I had running balance working until I merged recently to get the orchard changes.

Repro steps:

Execute account recovery using this UFVK:
```
uviewtest1tcygrtut692vqlx9nlyknx0fqq59am5vhaf97gxncqnfn87qrgey68777tumstc2lcp4r9yxd3fknkpmxtgw8awhcg40cw00ahvtaeqmpfqvjz6e3v234zsfvdvt6dm8dpzxv970wkdv2jrfm3t2m9cde9ry8mrxr286ns4yqwmcx3k4netqqhgldthnhzhlpg0lk00eruy4tf3fx3k9xn7fywppj8wyzjjc3dcrqe6kxnc6zxpfly9e2uk3k7jyy3n70zpj5zfheedzz0sw2pp96rvy9xt2dw94nplfx0usrwtshrmf5xwq84qcq459kvks5g28gvkxrjpujgc9gkjt5np5m4afruk0z8zlyd65hfqqu9pg3u9lkk26r7ad4l59yy3tn2xlmad42a6kee8l92ddj7tgf4fhv4x9thx7kf28jc6gvf3xr3lhtegd8ly590595g6dfh3w7nalmt8zx6yestgfqu9uvg8gkwkwmuc4u5jsecqu
```
(or, if you prefer, use the same seed phrase that I privately sent to @nuttycom over Signal).

Open the sqlite data file in DB Browser for SQLite and inspect the `v_tx_outputs` table:

![image](https://github.com/zcash/librustzcash/assets/3548/e18b77d5-5c75-477e-ba1d-7d2210eb4c91)

The selection in the above screenshot show the two outputs of a particular orchard transaction. The top one is change, but notice how `from_account_id` is `NULL`.
It's the same for _all_ change in this table. In fact you can see not a single row has both `from_account_id` and `to_account_id` set to non-NULL values, which is of course highly suspicious, as that would require every one of 21 transactions to have exactly no change.

In fact it isn't just change. One transaction in this account's history records an explicit 'send to self' transaction. Both the user amount and the change amount rows have `from_account_id` left at NULL.
![image](https://github.com/zcash/librustzcash/assets/3548/92c87126-8ed8-4482-8e34-f1846636d836)

**Comment by nuttycom** [comment]
There's something that I don't understand about your description of the issue here. The balance of an account is always exactly the sum of the unspent notes controlled by the account, as of a given block height. I need to understand better what you mean by "running balance", because you shouldn't be considering the value of sent notes at all in computing balance; you can report the sent value for each outgoing note, of course, but the balance of a transaction is always just the total value of spent notes minus the total value of received notes, including change.

**Comment by AArnott** [comment]
When I display balance for the user as an all-up value, I calculate balance as you say.
But when I'm showing transaction history, I have a running balance column that shows the impact each transaction has on the account balance. This is where the error shows up. Most financial applications show a running balance column and I think this is a very useful piece of UI, despite virtually no other wallets including it.

**Comment by AArnott** [comment]
Besides, running balance is only how the bug shows up most obviously in the app. But not having `from_account_id` initialized properly can screw up other things for the user as well, including simply which account to associated a transaction with, color-coding incoming vs. other transactions, etc.

**Comment by AArnott** [comment]
I added to the description to include a 'send to self' transaction for which there appears to be no evidence at all which account sent it. It just shows it as income to an account.

**Comment by AArnott** [comment]
`orchard_received_notes` shows the note that fed into the 'send to self' transaction as spent, as expected. 
`sent_notes` has no record of the 2 sent notes, which I believe explains why `v_tx_outputs` has NULL for `from_account_id`.

**Comment by AArnott** [comment]
The send-to-self transaction appears to miss the `sent_notes` table because of this filter:

https://github.com/zcash/librustzcash/blob/3c3fa6228939989bd237b5bdf72dcc22afddfeaa/zcash_client_sqlite/src/lib.rs#L1119-L1120

Send to self is both incoming and outgoing, but it is classified here only as incoming, and thus `wallet::put_sent_output` is never called.
I suspect the 'change' is similar, because the account transactions were created using Zingo, which doesn't support internal addresses, so it wouldn't qualify for WalletInternal, leaving it to qualify as both outbound and inbound, and so just like send-to-self, it'll miss the branch that stores it as outbound.

**Comment by nuttycom** [comment]
> Send to self is both incoming and outgoing, but it is classified here only as incoming, and thus `wallet::put_sent_output` is never called. I suspect the 'change' is similar, because the account transactions were created using Zingo, which doesn't support internal addresses, so it wouldn't qualify for WalletInternal, leaving it to qualify as both outbound and inbound, and so just like send-to-self, it'll miss the branch that stores it as outbound.

Send-to-self is a difficult issue at the level of the individual output, because you have to look at _all_ of the inputs to the transaction; a transaction can of course be funded by multiple parties, of which your wallet is only one.

**Comment by nuttycom** [comment]
The complete solution here would be something like:
* Add a method to `WalletRead` that is something like `detect_funding_accounts` that checks whether any of the wallet's accounts contributed value to the transaction.
* Remove the `from_account_id` column from the `sent_notes` table, and replace it with a `funding_accounts` junction table between `sent_notes` and `accounts`. 

This is probably a useful piece of work, but it's out of scope for the current SDK release.

**Comment by AArnott** [comment]
> if the value your wallet receives from the transaction is greater than the value that it contributes to the transaction, whatever subtraction you're doing is likely to result in a negative value.

The way you stated the arithmetic sounds wrong, which is perhaps why you say I'd get the wrong value. But it isn't exactly what I'm doing. I _am_ essentially taking "received - sent = balance delta", filtering out any parts of the transaction that don't apply to the account (and considering sent to include any applicable fees). 
The `v_transactions` view itself has an `account_balance_delta` column that is essentially the value I'm trying to calculate. And as you say, some of these values are negative. That's expected.  And while I _could_ perhaps just take the `account_balance_delta` column at face value instead of recalculating it, if I did, I might have missed this bug. And as I mention above, this bug impacts more than just balance... it prevents transactions from being associated with the account it was sent from, which in a multi-account wallet could mean that the transaction simply will not appear, although it _does_ impact balance.

**Comment by AArnott** [comment]
> The complete solution here would be 

A single transaction that is funded from _multiple_ zcash accounts, while possible by the consensus rules, doesn't sound like anything I've ever heard of being allowed by a zcash wallet. Are you aware of one? Given the seeming unlikelihood of it happening in the wild, and it not being creatable via librustzcash either, it seems very reasonable to consider this out of scope.

So long as we can support the case of a single account sending funds to itself (either explicitly or via implicit change) and _recognizing_ that the received funds came from itself, that is enough for me.

**Comment by nuttycom** [comment]
Can you see if https://github.com/zcash/librustzcash/pull/1306 fixes your issue?
