### ISSUE TITLE
Passive note management

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#1355]
@nuttycom:
> There's a very straightforward "passive note management" approach that we could take, which is to inspect the distribution of unspent notes prior to deciding upon the change note distribution. [...]
> And since we use the change system for shielding, we could use the same logic for shielding. I think that would capture a significant portion of the use cases.
> With those in place, you'd have it so that if you initially funded your wallet by sending to its transparent address, your experience would generally be pretty good; if you initially funded your wallet by sending to one of its shielded receivers, your UX would improve after your first spend and would then remain consistently better thereafter.

**Comment by nuttycom** [comment]
Completed to an initially satisfactory degree in #1580
