### ISSUE TITLE
Enable wallets build with the `zcash_client_backend` APIs to track multiple candidate chain tips

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#1366]
Both `zcashd` and `zcash_client_*` build their state around a canonical chain tip. When a reorg happens, that state is rewound to undo the effects of the old chain, and then the effects of the new chain are applied. If a miner battle is ongoing, this could result in repeated flip-flopping between chain states.

`zebrad` takes a different approach: it treats all data that is at least 100 blocks behind the current chain tip as "stable" (and writes it to persistent data storage), and then tracks all state about every candidate chain that exists within the last 100 blocks of the current best chain tip. This means that there are no rollbacks: new blocks always advance one of the existing candidate chains (or create a new one), and then when a new block advances a new chain beyond the existing "high water mark", the non-canonical chains that branched from the now-stable height are pruned and the stable block is persisted.

We should enable wallets built with `zcash_client_backend` to represent this in their wallet state. These wallets would maintain "alternative wallet views" based on the chains they have experienced, with the "real" wallet balance etc. coming from whatever is the current canonical chain tip.

Then at the stabilisation boundary, any now-pruned chains have their corresponding wallet states merged as appropriate into the remaining wallet states (e.g. any transaction that was only mined on a now-pruned chain would still be visible in the wallet, but as "expired unmined" or similar).

**Comment by nuttycom** [comment]
This isn't a blocker for zcashd wallet deprecation; the "full-node" wallet can do exactly as the light wallets do now. I think that making this multi-tip approach would increase complexity without really improving usability.

**Comment by nuttycom** [comment]
The complexity of implementing this is high, and it provides at best a negligible performance benefit.
