### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by levminder** [zcash/librustzcash#1384]
error[E0432]: unresolved imports `zcash_primitives::constants::CRH_IVK_PERSONALIZATION`, `zcash_primitives::constants::PROOF_GENERATION_KEY_GENERATOR`, `zcash_primitives::constants::SPENDING_KEY_GENERATOR`
 --> src/rust/src/sapling/spec.rs:9:17
  |
9 | ...::{CRH_IVK_PERSONALIZATION, PROOF_GENERATION_KEY_GENERATOR, SPENDING_KEY_GENERATOR},
  |       ^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^ no `SPENDING_KEY_GENERATOR` in `constants`
  |       |                        |
  |       |                        no `PROOF_GENERATION_KEY_GENERATOR` in `constants`
  |       no `CRH_IVK_PERSONALIZATION` in `constants`

error[E0432]: unresolved imports `zcash_primitives::zip32::sapling_address`, `zcash_primitives::zip32::sapling_derive_internal_fvk`, `zcash_primitives::zip32::sapling_find_address`
 --> src/rust/src/sapling/zip32.rs:3:19
  |
3 |     zip32::{self, sapling_address, sapling_derive_internal_fvk, sapling_find_address},
  |                   ^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^ no `sapling_find_address` in the root
  |                   |                |
  |                   |                no `sapling_derive_internal_fvk` in the root
  |                   no `sapling_address` in the root

error[E0433]: failed to resolve: could not find `ExtendedSpendingKey` in `zip32`
  --> src/rust/src/sapling/zip32.rs:33:22
   |
33 |     let xsk = zip32::ExtendedSpendingKey::master(seed);
   |                      ^^^^^^^^^^^^^^^^^^^ could not find `ExtendedSpendingKey` in `zip32`
   |
help: consider importing one of these items
   |
1  | use crate::sapling::ExtendedSpendingKey;
   |
1  | use sapling::zip32::ExtendedSpendingKey;
   |
help: if you import `ExtendedSpendingKey`, refer to it directly
   |
33 -     let xsk = zip32::ExtendedSpendingKey::master(seed);
33 +     let xsk = ExtendedSpendingKey::master(seed);
   |

error[E0433]: failed to resolve: could not find `ExtendedSpendingKey` in `zip32`
  --> src/rust/src/sapling/zip32.rs:44:16
   |
44 | ...   zip32::ExtendedSpendingKey::read(&xsk_parent[..]).expect("valid ExtendedSpendingKey");
   |              ^^^^^^^^^^^^^^^^^^^ could not find `ExtendedSpendingKey` in `zip32`
   |
help: consider importing one of these items
   |
1  | use crate::sapling::ExtendedSpendingKey;
   |
1  | use sapling::zip32::ExtendedSpendingKey;
   |
help: if you import `ExtendedSpendingKey`, refer to it directly
   |
44 -         zip32::ExtendedSpendingKey::read(&xsk_parent[..]).expect("valid ExtendedSpendingKey");
44 +         ExtendedSpendingKey::read(&xsk_parent[..]).expect("valid ExtendedSpendingKey");
   |

error[E0433]: failed to resolve: could not find `ExtendedSpendingKey` in `zip32`
  --> src/rust/src/sapling/zip32.rs:59:16
   |
59 | ...   zip32::ExtendedSpendingKey::read(&xsk_external[..]).expect("valid ExtendedSpendingKe...
   |              ^^^^^^^^^^^^^^^^^^^ could not find `ExtendedSpendingKey` in `zip32`
   |
help: consider importing one of these items
   |
1  | use crate::sapling::ExtendedSpendingKey;
   |
1  | use sapling::zip32::ExtendedSpendingKey;
   |
help: if you import `ExtendedSpendingKey`, refer to it directly
   |
59 -         zip32::ExtendedSpendingKey::read(&xsk_external[..]).expect("valid ExtendedSpendingKey");
59 +         ExtendedSpendingKey::read(&xsk_external[..]).expect("valid ExtendedSpendingKey");
   |

error[E0433]: failed to resolve: could not find `ExtendedFullViewingKey` in `zip32`
  --> src/rust/src/sapling/zip32.rs:72:30
   |
72 |     let xfvk_parent = zip32::ExtendedFullViewingKey::read(&xfvk_parent[..])
   |                              ^^^^^^^^^^^^^^^^^^^^^^ could not find `ExtendedFullViewingKey` in `zip32`
   |
help: consider importing this struct
   |
1  | use sapling::zip32::ExtendedFullViewingKey;
   |
help: if you import `ExtendedFullViewingKey`, refer to it directly
   |
72 -     let xfvk_parent = zip32::ExtendedFullViewingKey::read(&xfvk_parent[..])
72 +     let xfvk_parent = ExtendedFullViewingKey::read(&xfvk_parent[..])
   |

error[E0433]: failed to resolve: could not find `sapling` in `zip32`
  --> src/rust/src/sapling/zip32.rs:89:21
   |
89 |     let dk = zip32::sapling::DiversifierKey::from_bytes(dk);
   |                     ^^^^^^^ could not find `sapling` in `zip32`
   |
help: consider importing this struct
   |
1  | use sapling::zip32::DiversifierKey;
   |
help: if you import `DiversifierKey`, refer to it directly
   |
89 -     let dk = zip32::sapling::DiversifierKey::from_bytes(dk);
89 +     let dk = DiversifierKey::from_bytes(dk);
   |

error[E0433]: failed to resolve: could not find `sapling` in `zip32`
   --> src/rust/src/sapling/zip32.rs:102:21
    |
102 |     let dk = zip32::sapling::DiversifierKey::from_bytes(dk);
    |                     ^^^^^^^ could not find `sapling` in `zip32`
    |
help: consider importing this struct
    |
1   | use sapling::zip32::DiversifierKey;
    |
help: if you import `DiversifierKey`, refer to it directly
    |
102 -     let dk = zip32::sapling::DiversifierKey::from_bytes(dk);
102 +     let dk = DiversifierKey::from_bytes(dk);
    |

error[E0433]: failed to resolve: could not find `sapling` in `zip32`
   --> src/rust/src/sapling/zip32.rs:117:21
    |
117 |     let dk = zip32::sapling::DiversifierKey::from_bytes(dk);
    |                     ^^^^^^^ could not find `sapling` in `zip32`
    |
help: consider importing this struct
    |
1   | use sapling::zip32::DiversifierKey;
    |
help: if you import `DiversifierKey`, refer to it directly
    |
117 -     let dk = zip32::sapling::DiversifierKey::from_bytes(dk);
117 +     let dk = DiversifierKey::from_bytes(dk);
    |

error[E0433]: failed to resolve: could not find `sapling` in `zip32`
   --> src/rust/src/sapling/zip32.rs:129:21
    |
129 |     let dk = zip32::sapling::DiversifierKey::from_bytes(dk);
    |                     ^^^^^^^ could not find `sapling` in `zip32`
    |
help: consider importing this struct
    |
1   | use sapling::zip32::DiversifierKey;
    |
help: if you import `DiversifierKey`, refer to it directly
    |
129 -     let dk = zip32::sapling::DiversifierKey::from_bytes(dk);
129 +     let dk = DiversifierKey::from_bytes(dk);
    |

error[E0603]: crate `sapling` is private
  --> src/rust/src/sapling/spec.rs:11:5
   |
11 |     sapling::{
   |     ^^^^^^^ private crate
   |
note: the crate `sapling` is defined here
  --> /mnt/datafedora/zcash/depends/x86_64-pc-linux-gnu/share/../vendored-sources/zcash_primitives/src/lib.rs:26:5
   |
26 | use sapling;
   |     ^^^^^^^

error[E0603]: crate `sapling` is private
  --> src/rust/src/sapling/zip32.rs:2:5
   |
2  |     sapling::{keys::FullViewingKey, Diversifier},
   |     ^^^^^^^ private crate
   |
note: the crate `sapling` is defined here
  --> /mnt/datafedora/zcash/depends/x86_64-pc-linux-gnu/share/../vendored-sources/zcash_primitives/src/lib.rs:26:5
   |
26 | use sapling;
   |     ^^^^^^^

error[E0603]: tuple struct constructor `DiversifierIndex` is private
   --> src/rust/src/sapling/zip32.rs:103:20
    |
103 |     let j = zip32::DiversifierIndex(j);
    |                    ^^^^^^^^^^^^^^^^ private tuple struct constructor
    |
   ::: /mnt/datafedora/zcash/depends/x86_64-pc-linux-gnu/share/../vendored-sources/zip32/src/lib.rs:153:29
    |
153 | pub struct DiversifierIndex([u8; 11]);
    |                             -------- a constructor is private if any of the fields is private
    |
note: the tuple struct constructor `DiversifierIndex` is defined here
   --> /mnt/datafedora/zcash/depends/x86_64-pc-linux-gnu/share/../vendored-sources/zip32/src/lib.rs:153:1
    |
153 | pub struct DiversifierIndex([u8; 11]);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: tuple struct constructor `DiversifierIndex` is private
   --> src/rust/src/sapling/zip32.rs:118:20
    |
118 |     let j = zip32::DiversifierIndex(j);
    |                    ^^^^^^^^^^^^^^^^ private tuple struct constructor
    |
   ::: /mnt/datafedora/zcash/depends/x86_64-pc-linux-gnu/share/../vendored-sources/zip32/src/lib.rs:153:29
    |
153 | pub struct DiversifierIndex([u8; 11]);
    |                             -------- a constructor is private if any of the fields is private
    |
note: the tuple struct constructor `DiversifierIndex` is defined here
   --> /mnt/datafedora/zcash/depends/x86_64-pc-linux-gnu/share/../vendored-sources/zip32/src/lib.rs:153:1
    |
153 | pub struct DiversifierIndex([u8; 11]);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `incrementalmerkletree::Hashable`
 --> src/rust/src/sapling/spec.rs:5:5
  |
5 | use incrementalmerkletree::Hashable;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `merkle_tree::HashSer`
  --> src/rust/src/sapling/spec.rs:10:5
   |
10 |     merkle_tree::HashSer,
   |     ^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0432, E0433, E0603.
For more information about an error, try `rustc --explain E0432`.
warning: `librustzcash` (lib) generated 2 warnings
error: could not compile `librustzcash` due to 14 previous errors; 2 warnings emitted

**Comment by str4d** [comment]
The errors above are clearly from https://github.com/zcash/zcash, not this repository. It might be that you were trying to build `zcashd` with the latest state from this repository; it is expected that you would need to make changes to fix errors, as there are multiple breaking changes in the current working state of this repository.
