### ISSUE TITLE
Alter the scan_block API to support arbitrary FVKs

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#141]
`zcash_client_backend::welding_rig::scan_block` currently takes a slice of `ExtendedFullViewingKey`, using the indices within the slice as the account number. This makes the assumption that the caller has a single tree of keys and is using them all sequentially. In practice there may be situations where we want to be able to scan arbitrary `ExtendedFullViewingKey`s (e.g. auditing situations), which require either non-sequential account numbers, or possibly no account number at all.

**Comment by nuttycom** [comment]
Fixed in f59124ce1
