### ISSUE TITLE
Standalone Key Derivation

### ISSUE THREAD

**Issue by gmale** [zcash/librustzcash#143]
## Request
As a wallet developer, I want to have a way to generate seeds and keys without storing state so that I can manage sensitive information consistently in my app and avoid unknown behaviors in order to better comply with audits.

#### Origin
Without prescribing implementation, it has been requested that we provide an API to "pass in a seed and return a bundle that contains the keys and address, without storing anything to disk" because this is similar to how other coin APIs behave. From there, the wallet maker will provide those keys to use any sensitive APIs, later.

#### Topic: Seed derivation
We will have to decide whether seed derivation is out of scope for the SDK. Wallet makers would find value in at least having the basic APIs. So it might be reasonable to mimic `zecwallet-cli` and, at least, [provide APIs for creating BIP39 seeds and working with seed phrases](https://github.com/adityapk00/zecwallet-light-cli/blob/11bc928f8d130c28f17b65324dd85f2dba1911df/lib/src/lightwallet.rs#L180). Perhaps PRs could be submitted for just adding that functionality to `zcash_client_backend`.

#### Topic: Key Derivation
Some options for providing keys without saving state:

1. given a seed -> return just the sapling extended spending key
    - from there, also provide APIs to go from extsk -> extfvk and from extfvk -> address
1. given a seed -> return a bundle of extsk + extfvk
    - from there, also provide APIs extfvk -> address
1. given a seed -> return a bundle of extsk + extfvk + address

#### Topic: Accounts
The APIs will need to consider how accounts are created. Either we specify the total number of accounts once or we provide APIs for creating one account and then adding other accounts, later.

#### Topic: SDK  Size
The size of  the core  library will be an important  factor to consider. If we can leverage crates that are already listed as dependencies that would be ideal, rather than pulling in new things and adding to the bulk of the core library. Alternatively, we may  want to provide a way to optionally include BIP39 and Mnemonic support, if and only if that will save substantial size.

##  Criteria
- Librustzcash seed generation and key derivation APIs are documented
- Keys can be generated without storing state in `librustzcash`
- New APIs are exposed in the Android / iOS SDKs (i.e. added to the welding layer)
- The size of the core library is not substantially increased

**Comment by gmale** [comment]
Note: this may need to be split into two issues, one for everything related to seeds and another for everything related to keys. However, the code is all closely related so I've just put everything under one issue, for now.

**Comment by str4d** [comment]
> **Topic: Key Derivation**
>
>Some options for providing keys without saving state:
>
> 1. given a seed -> return just the sapling extended spending key
>     - from there, also provide APIs to go from extsk -> extfvk and from extfvk -> address


We already have this. `zcash_client_backend::keys::spending_key` returns an `ExtendedSpendingKey` which can then be converted into an `ExtendedFullViewingKey` and `PaymentAddress`. Turning any of these into its string encoding can be done with the methods in the `zcash_client_backend::encoding` module.

> **Topic: Accounts**
>
> The APIs will need to consider how accounts are created. Either we specify the total number of accounts once or we provide APIs for creating one account and then adding other accounts, later.

The above function takes an account number as a parameter, returning the spending key for that account. Generating spending keys for a bulk group of account numbers is a trivial map (which is [exactly what the Android SDK does](https://github.com/zcash/zcash-android-wallet-sdk/blob/bb824450b0b560810e8718cad9f46cbef0e4a722/src/main/rust/lib.rs#L96-L99)).

**Comment by gmale** [comment]
Good points. One thing I tried to articulate but failed to make clear is that most of these things exist at the `librustzcash` level but not in the SDKs. Rust code would need to be added to the welding layer.

For instance, I tried to make a `welding` function taking an array of extfvks as strings instead of a seed. [I got close but failed](https://github.com/zcash/zcash-android-wallet-sdk/commit/07b49bd3318df3eb235449d005d0bdc479141d52). So I could probably use help there. I'll try leveraging the `zcash_client_backend::encoding` module.

----

To clarify, here are the specific requests we've received and what they might entail:
#### As a developer, using the SDK, I'd like to pass in a seed and get back a bundle of keys.
- functionality for this exists in `librustzcash` 
- code needs to be added to the Rust welding layer to expose this functionality
- a decision needs to be made around the structure of the returned bundle
    - does it also contain the address (like monero)?
    - does it also contain the viewing keys (thereby the sqlite crate no longer stores this)?
- SDK changes should be made to wrap and incorporate this functionality during wallet creation

#### As a developer, using the SDK, I'd like to pass in a viewing key and get back an address.
- functionality for this exists in `librustzcash` 
- code needs to be added to the Rust welding layer to expose this functionality
- SDK changes should be made to wrap and incorporate this functionality when providing an address

#### As a developer, using the SDK, I'd like to create an account with just the viewing key.
- functionality for this exists in `librustzcash` 
- code needs to be added to the Rust welding layer to expose this functionality
- this may have other implications
    - it may free the sqlite crate from storing these keys. reducing the amount of state that librustzcash maintains is a common request.
    - we want to encourage using only one address for shielded transactions but having lots of accounts might indirectly encourage unintended usage

**Comment by gmale** [comment]
Update: as it relates to the 4th item above (having all the tools), after discussions with @str4d earlier this week, it seems reasonable for this functionality to exist outside the SDK as a separate, optional module.

Rationale:
- Mulitcurrency wallet partners will already have robust implementations for seed creation
  - These partners may want to opt out of adding seed-related features
  - Making it optional avoids redundancy and reduces final app size for some partners
- Seed Phrases use [word lists in a variety of languages](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md)
  - Android and iOS platforms have built-in mechanisms for handling locales
  - it would be better to do the locale work at the platform level, rather than in Rust
- This frees librustzcash from having to be concerned with seed derivation, which seems appropriate

Tradeoffs:
- This means each "SDK" will have to re-implement seed derivation
  - This is mitigated by the fact that many libraries exist for both Kotlin and Swift for this
  - ECC may want to create and maintain its own BIP 39 library since the cryptography is not very difficult

**Comment by gmale** [comment]
We have implemented stand-alone key derivation outside of librustzcash so this issue is no longer valid.
