### ISSUE TITLE
Ensure symmetry of transparent output handling between `put_blocks`, `store_decrypted_tx` and `store_sent_tx`

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#1434]
> AFAICT (at least as of the first commit in the PR), this `NULL AS from_account_id` is preserved, because there is still an asymmetry between transparent and shielded (we are not inserting transactions into both sent and received tables for transparent, in the same way we do for shielded). I think that asymmetry needs fixing prior to the next release (if not in this PR).

_Originally posted by @str4d in https://github.com/zcash/librustzcash/pull/1402#discussion_r1648028219_

_See also https://github.com/zcash/librustzcash/pull/1402#discussion_r1648037109_

**Comment by daira** [comment]
Did merging #1402 fix this, or is there more to do?

**Comment by str4d** [comment]
There is still more to do; e.g. `store_decrypted_tx` does not update the received transparent outputs table. This causes an issue with ZIP 320 transactions, but it is also one that we might decide to stick with for the next release. I've marked this issue as blocking #1231 for us to decide whether we do finish this or bump it.
