### ISSUE TITLE
zcash_address::kind::unified::address::Address::can_receive_memo does not account for whether Orchard is disabled

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#1438]

**Comment by nuttycom** [comment]
`zcash_address` does not have feature flagging that controls the availability of `orchard` dependencies; it always implements handling for all Zcash address types. If this determination needs to be made in a context where only specific protocol support is enabled, it should be made by decoding to a protocol address and then checking whether that protocol address supports receiving memos.
