### ISSUE TITLE
Field name doesn't match the protocol spec.

### ISSUE THREAD

**Issue by zancas** [zcash/librustzcash#145]
Should [the header field that references the previous block](https://github.com/zcash/librustzcash/blob/40d22ea2cc3a084ce31205e79a9290983f5b2153/zcash_primitives/src/block.rs#L55) be named [the hashPrevBlock field](https://github.com/zcash/zips/blob/89de83447a1cd39c75cf303dda89f57c722d93df/protocol/protocol.tex#L2789) per the protocol?

Or should the protocol be updated to reflect the state of the reference implementation?

**Comment by daira** [comment]
I don't see any need to update the protocol here. I'm not sure the reference implementation needs to be changed either; it's fairly clear which field `prev_block` refers to.
