### ISSUE TITLE
Precisely document same-UFVK errors on account creation and ensure they are per-component

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#1474]
This is an issue with #1465 found in post-hoc review.

_Originally posted by @daira in https://github.com/zcash/librustzcash/pull/1465#discussion_r1695972600_

> Should this say "If an account created via [`WalletWrite::create_account`] or imported via [`WalletWrite::import_account_ufvk`] or [`WalletWrite::import_account_hd`] already exists in the wallet with the same UFVK (which will also be the case for accounts with the same seed), an error will be returned." ?
>
> This differs from the current wording because (I think) it is not the case that the creation or import has to be in any particular order; any of these three methods will fail if it produces a duplicate UFVK, regardless of which of them was used to create the existing account. At least, if that's not the case then it is a bug.
>
> Also, do we actually mean "same UFVK" here, or do we mean that there will be a failure if *any component* of the UFVK matches that of an existing account? In the case of an account where we don't know the seed, the imported UFVK can't include components that are not known yet, and *may not* include some existing components (I don't know whether the latter is supported).

_Originally posted by @daira in https://github.com/zcash/librustzcash/pull/1465#discussion_r1695982562_

> I think the doc for each of the three account creation/import methods should call out that it fails when there is a duplicate UFVK, even if that's redundant with the `WalletWrite` doc. Note that it is possible to hit this case even if you only use one of the three methods, and there might be implementors who only read the documentation of the methods they are using (because they haven't reached [this page](https://hmpg.net/) yet).

**Comment by str4d** [comment]
> Also, do we actually mean "same UFVK" here, or do we mean that there will be a failure if any component of the UFVK matches that of an existing account? In the case of an account where we don't know the seed, the imported UFVK can't include components that are not known yet, and may not include some existing components (I don't know whether the latter is supported).

Currently, the three uniqueness constraints that `zcash_client_sqlite` implements are:
- same `(seed, ZIP 32 account index)`
- same UFVK
- same UIVK (which we can consider equivalent to "same UFVK")
https://github.com/zcash/librustzcash/blob/7f7b685b99132505a0fe4ba588f329e3516e9669/zcash_client_sqlite/src/wallet/db.rs#L25-L34
https://github.com/zcash/librustzcash/blob/7f7b685b99132505a0fe4ba588f329e3516e9669/zcash_client_sqlite/src/wallet/db.rs#L55-L60
https://github.com/zcash/librustzcash/blob/7f7b685b99132505a0fe4ba588f329e3516e9669/zcash_client_sqlite/src/wallet.rs#L418-L431

We do cache the individual components in the table, but only the `ufvk` and `uivk` columns are forced to be unique.

Specifically, what this means is that we will correctly detect conflicts between `WalletWrite::create_account` and `WalletWrite::import_account_hd`, but we will not reliably detect conflicts between those two and `WalletWrite::import_account_ufvk`. We should decide what we want to do in the latter case, before the next release.

**Comment by nuttycom** [comment]
I think that what we should do is use a query to check against the individual components. We may _also_ want to add a uniqueness constraint, but I prefer not to rely upon constraint violation errors for control flow; reporting to the user that a conflict has been identified should be the result of an explicit check.
