### ISSUE TITLE
Research Spike: Design work on Data Access API

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/librustzcash#150]

**Comment by alchemydc** [comment]
See https://github.com/zcash/librustzcash/issues/150

**Comment by alchemydc** [comment]
Spike is likely able to be finished within a single sprint.   Will require peering / meeting with Kevin as well as other engineers on Core.

**Comment by str4d** [comment]
I synthesised the various requirements from the issue and sketched out a draft design for the Rust components. I met with @gmale, @pacu, and Aditya today to discuss the issue, and a partial outcome was that they were happy with the draft design as the logic core. It would likely be wrapped in various different ways (e.g. directly via FFI, or inside a gRPC server) depending on the usage context, but for the most part the Rust core design seems extensible enough to handle this.

Next steps:
- Identity what is necessary to store/retrieve at the data level.
- Work out the initial Wallet API surface.
- Figure out how to handle block data synchronization, and whether this should be synchronous or not.
  - Initially this will probably be two synchronous API calls, one that is per-block and another that is per-block-range, which make callbacks internally for status updates.
- Map out the callbacks the clients care about (e.g. "block scanned", "balance changed", "transaction received")
- Implement the above in an initial prototype.

I'll update the issue with a fuller sketch in the next sprint (which starts tomorrow).
