### ISSUE TITLE
Implement NU-awareness

### ISSUE THREAD

**Issue by gmale** [zcash/librustzcash#152]
## Request
As a developer, using the library, I would like to build transactions that can be successfully broadcast to the network I am on so that the wallet I build handles network upgrades more robustly.

#### Implementation Notes
Per discussions with @str4d this should simply require tying the consensus branch ID to the network type and block height.

## Criteria
- transactions built using the library can be successfully broadcast on all combinations of `Sapling | Blossom` and `Testnet | Mainnet`
- the feature is built such that future Network Upgrades are handled, as well

**Comment by gmale** [comment]
Currently, [zecwallet-light](https://github.com/adityapk00/zecwallet-light-cli/blob/11bc928f8d130c28f17b65324dd85f2dba1911df/lib/src/lightwallet.rs#L1310) handles this by accepting a consensus branch id whenever it constructs a transaction.

So it seems like there are two approaches we could take:
1. Pass in Consensus Branch ID as a parameter that's read from the server
2. Derive Consensus Branch ID based on known information (latest height and network type)

Each has pros and cons and of course, we can code it in a way to allow both (accept a parameter but if none is provided, derive the default).

**Comment by str4d** [comment]
I've enabled both approaches in #174. Transaction building now takes a `BranchId` enum, which can be constructed in several ways:

```rust
let value_from_server: u32 = ...;
let consensus_branch_id: BranchId = value_from_server.try_into()?;
```

```rust
let height_from_server = ...;
let consensus_branch_id = BranchId::for_height::<MainNetwork>(height);
```
