### ISSUE TITLE
New sqlite release has undocumented breaking change: v_tx_outputs.to_address is NULL for transparent inputs

### ISSUE THREAD

**Issue by AArnott** [zcash/librustzcash#1525]
The rewrite of utxos to transparent_received_outputs seems to have broken the v_tx_outputs view, in that to_address is now NULL for the transparent ones.
In fact it seems the to_address is hard-wired in that view now to always be NULL for inputs, where before it was only null for shielded inputs but set to utxos.address for transparent inputs.

**Comment by AArnott** [comment]
I rely on the old behavior, and will have to workaround this by creating a new view,

**Comment by str4d** [comment]
#1547 added the missing information to the changelog. As requested previously, if there isn't a Rust API already for accessing this, and you have a use case for accessing it, please open an issue for creating such an API that describes the use case.
