### ISSUE TITLE
Bug in minimumShieldingConfirmations: UInt32 = 1 (it still requires 10 confirmations to be able to shield)

### ISSUE THREAD

**Issue by true-jared** [zcash/librustzcash#1572]
- even though SDK has 1 confirmation set let minimumShieldingConfirmations: UInt32 = 1 we still need to wait 10 confirmations

How to reproduce:
- I tapped a button to shield my funds, it:
- created a transaction in a pending state with is_shielding TRUE
- after 1st confirmation, it flipped to sending instead of shielding, I checked the DB and there is no TRUE anymore (see the DB)
- after 10 confirmations, it flipped to sent
- when I restore the same wallet, I see shielded again

Few more observations:
- when I try to restore the wallet on a different simulator while it’s still waiting on 10 confirmations and should be shielding funds but it’s sending, I see correct state restored.. so restore is able to bring the TRUE flag back but where it matters it’s broken

- db export shared via Slack here: https://zcash.slack.com/archives/C02C1GZ0R6F/p1724835111523729

**Comment by nuttycom** [comment]
We had identified a couple of bugs, one in `get_wallet_summary` and another in the wallet application, both of which were fixed but did not fix this issue; this requires additional analysis.

**Comment by nuttycom** [comment]
Related to #1413

**Comment by daira** [comment]
I'm looking at #1570 (the proposed fix for #1411), and it seems like without the changes in that PR, `transparent::add_transparent_account_balances` does not take account of `min_confirmations` (as passed to `get_wallet_summary`) at all. I think that is likely to be the problem, in which case it will be fixed by #1570.

**Comment by nuttycom** [comment]
> I'm looking at #1570 (the proposed fix for #1411), and it seems like without the changes in that PR, `transparent::add_transparent_account_balances` does not take account of `min_confirmations` (as passed to `get_wallet_summary`) at all. I think that is likely to be the problem, in which case it will be fixed by #1570.

Since it does not take account of `min_confirmations`, it should be reporting all notes, so I don't see how this can be related.

**Comment by daira** [comment]
Sorry, you're right. `unshielded_balance` will currently include both spendable and unspendable UTXOs.

**Comment by daira** [comment]
> Related to #1413

It seems like a duplicate to me. Let's copy the description of this bug there and merge them. I don't think having two issues helps even if there are multiple causes; both current issues are about the user-visible behaviour as a consequence of using `zcash_client_{backend,sqlite}`, so they are duplicates regardless.

**Comment by daira** [comment]
Merging into #1413.
