### ISSUE TITLE
Dynamic confirmation height

### ISSUE THREAD

**Issue by braddmiller** [zcash/librustzcash#178]
As a wallet developer I'd like to be able to set the minimum number of confirmations required to spend Sapling funds in my wallet front end.

Context:
Currently the confirmation height to allow funds to be spendable in our mobile apps are set by librustzcash at 10. This logic should be dynamic and respond to input from the wallet developer instead of being hardcoded at the librustzcash level.

Criteria:
- [ ] librustzcash can set the confirmation height dynamically for funds based on an input from a library that uses librustzcash (the Android SDK for instance).

**Comment by str4d** [comment]
See also https://github.com/zcash/zcash/issues/1614 which links to security issues and UX around this problem (which motivated fixing the confirmation level at 10 in the first place).

**Comment by braddmiller** [comment]
We'll stick with 10 for now. This can be shelved until more conversations and research around confirmation heights in general have been had.

**Comment by nuttycom** [comment]
This is done with respect to the `librustzcash` layers; the confirmation depth is currently hardcoded in the SDK layers, but we're moving to ZIP 315 trust policies in any case so for practical purposes this is done.
