### ISSUE TITLE
Refactor RedJubjub to serialize the pubkey internally

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#179]
The current implementation serializes `R || M` because this was how RedJubjub was originally specified. Late in the Sapling development process, this was altered to `R || vk || M` to make a security proof easier. The code was not altered at the time because all RedJubjub callers were already prepending pubkeys to their messages before signing, which is functionally identical.

We should refactor RedJubjub to instead serialize `vk` internally, so that the callsites do not need to care, and the implementation more closely matches the spec.

**Comment by daira** [comment]
More precisely, it's not that the security proof was made easier; it's that *Strong* Unforgeability under Randomised Keys does not hold generically unless the key is included.

**Comment by daira** [comment]
The `redjubjub` crate was refactored to be a wrapper over the `reddsa` crate in https://github.com/ZcashFoundation/redjubjub/pull/152 . The `reddsa` crate does do the prefixing itself, [for signing](https://github.com/ZcashFoundation/reddsa/blob/c6d1a9989f5440be70e9593bbb15e033bed8bd2f/src/signing_key.rs#L116-L129) and [for verification](https://github.com/ZcashFoundation/reddsa/blob/c6d1a9989f5440be70e9593bbb15e033bed8bd2f/src/verification_key.rs#L156). So there is nothing more to do here.
