### ISSUE TITLE
Tech Debt: Refactor Android / iOS welding layers to pull as much logic into librustzcash as possible

### ISSUE THREAD

**Issue by gmale** [zcash/librustzcash#187]
At some point, we should refactor the lib.rs files on Android and iOS such that they contain as little code as possible. For instance, this [create to address function on the Android side](https://github.com/zcash/zcash-android-wallet-sdk/blob/bebe0cf4e729b0527af38184eeda5ba9317067d3/src/main/rust/lib.rs#L491) contains some logic that we don't want to duplicate in iOS. Particularly, the parameter validation. We probably want to create functions that safely convert from JVM types to rust types and then simply invoke a shared method that does the rest.

**Comment by gmale** [comment]
Note: str4d has done an excellent job of getting most of the common logic out of the welding layer and into Librustzcash. It's just that once the Android / iOS dogfood apps are functional, we should take another pass at the lib.rs files in each project and be creative about what other code we can remove. This may require coming up with a common way for handling errors and return values for each function.

**Comment by gmale** [comment]
These changes should probably go into a separate crate.

**Comment by geffenz** [comment]
Adding to SDK Refactor EPIC.

**Comment by nuttycom** [comment]
We've done a lot of this, and anything else that we want to do here should be opened as a more specific issue.
