### ISSUE TITLE
Expose decrypt_transaction in the rust welding layers

### ISSUE THREAD

**Issue by braddmiller** [zcash/librustzcash#201]
As of #176 a function, `decrypt_transaction` is in librustzcash but is not yet available to the SDKs for iOS or Android.

The results of calling the `decrypt_transaction` function need to be stored and accessed via the `sqlite_crate`.

Our end goal is to provide access to memos in the mobile SDKs.

**Comment by gmale** [comment]
Ideally, we could do this in a way that minimizes duplication in the iOS / Android welding layers. In other words, the sqlite crate would do most of the heavy lifting and all we are really doing is exposing a function or two in the RustBackend `lib.rs` files on Android/iOS.

**Comment by LarryRuane** [comment]
Keep in mind that memos are per-transaction-output, not per-transactions. So they must be accessed by (for example and probably most reasonably) `txid` (hash) and output index (integer). A wallet that's able to decode one output's memo will in general not be able to decode other outputs' memos from the same transaction.

**Comment by pacu** [comment]
there's the  tech debt comment that relates to what @gmale said
#187

**Comment by alchemydc** [comment]
>In summary, there is a function that decrypts entire transactions that Str4d added to librustzcash a couple of months ago. It creates a struct that contains a bunch of information, but importantly for the wallet, it contains memos. So now we have a way to decrypt the transactions, we can receive transactions from lightwalletd, but the SDKs don’t yet have access to this information.

**Comment by braddmiller** [comment]
This looks like a duplicate of #184
