### ISSUE TITLE
Reorg Rollback Improvements

### ISSUE THREAD

**Issue by gmale** [zcash/librustzcash#208]
#### Steps

1. Alice sends funds to Bob
2. The transaction is mined in block N
3. Sometime later, a reorg occurs that includes block N
4. Both Alice and Bob's wallets detect the reorg and attempt to repair it by rolling back their local data
5. After rolling back, each wallet begins to re-process the set of rollback blocks
6. Processing fails due to foreign key constraints
7. Both Alice and Bob's wallets get bricked, unable to scan or send funds!!!

#### Details
Currently, the evidence suggests that handling a reorg leaves the sqlite database in a state where foreign key constraints get violated, which results in the inability to insert data whenever reprocessing blocks that were rolled back as a result of a reorg. This problem only presents itself when the blocks that were rolled back contain transactions that match the wallet.

More investigation is needed but we may need to update the rollback logic to leave the database in an identical state, compared to if we had never downloaded the blocks in question.

**_Update 2/18/2020_**:
We have isolated the problem. It occurs when we are trying to `insert` a received note pointing to a transaction that already exists, rather than `update` it. The first fix is to also delete from the `received_notes` table during a rollback, which prevents this situation from occurring. The next (optional) fix is to also change the `insert` to an `update` when appropriate, which would avoid the foreign key constraint problem if the wallet ever gets in this state, somehow.

**Comment by gmale** [comment]
To put this more precisely, given a database D<sub>n</sub> containing information related to all blocks with height between SAPLING_ACTIVATION and n, and a function R(D, s), which performs a rollback of size s on database D:

R(D<sub>n</sub>,s) &#8801; D<sub>n - s</sub>

for all values of 

n >= SAPLING_ACTIVATION
0 < s < MAX_ROLLBACK_SIZE


In other words, rollbacks result in a state that is _identical_ to having never processed the rollback blocks.

**Comment by nuttycom** [comment]
We now use upserts instead of inserts for transaction creation.
