### ISSUE TITLE
Tx builder adds Binding Signature even for t->t transactions

### ISSUE THREAD

**Issue by adityapk00** [zcash/librustzcash#220]
If I understand it correctly, the protocol specifies that binding signatures should not be present for t -> t transactions - i.e., transactions that don't have any sapling spends or outputs. 

However, the builder code here seems to add the binding signature for all transactions, even for t->t transactions: https://github.com/zcash/librustzcash/blob/master/zcash_primitives/src/transaction/builder.rs#L647

This causes light clients sending pure t->t transactions to fail. 

There should be a check around it, something like:
```
let needs_binding_sig = !spends.is_empty() || !outputs.is_empty();
if needs_binding_sig {
 self.mtx.binding_sig = Some(
            prover
                .binding_sig(&mut ctx, self.mtx.value_balance, &sighash)
                .map_err(|()| Error::BindingSig)?,
        );
} else {
  self.mtx.binding_sig = None;
}
```

Is my understanding correct? Happy to make a PR.

cc: @str4d , @daira, @gmale

**Comment by daira** [comment]
Yes, the binding signature is present [iff the transaction version is >= 4 and nShieldedSpend + nShieldedOutput > 0](https://zips.z.cash/protocol/protocol.pdf#txnencoding)
