### ISSUE TITLE
Bring in Bolt TZE

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#226]
The Bolt extensions is currently in https://github.com/boltlabs-inc/librustzcash on top of my initial `zip-wtps` branch. Once zcash/zips#224 is complete, we should rework that branch to use the updated TZE logic.

**Comment by nuttycom** [comment]
In progress work in https://github.com/nuttycom/librustzcash/tree/bolt-zip-tzes

**Comment by nuttycom** [comment]
Currently not planned; reopen if this becomes relevant.
