### ISSUE TITLE
Set up reusable testing support crates

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#233]
We have various places within the current crates where we mock out interfaces or repeatedly implement common test-harness operations (e.g. creating a fake note to spend, or bellman's `TestConstraintSystem`). We should extract those into testing crates, that can be used as dev-dependencies by both us and third parties. This [does not create a dependency cycle](https://stackoverflow.com/questions/41700543/can-we-share-test-utilites-between-crates/42329538#42329538).

**Comment by nuttycom** [comment]
This is effectively served by #1543 et al.
