### ISSUE TITLE
bellman: why is the first entry of pvk.ic skipped?

### ISSUE THREAD

**Issue by hdevalence** [zcash/librustzcash#255]
https://github.com/zcash/librustzcash/blob/f55f094ef69c2caeaa941bcf851dac8cb5fa9942/bellman/src/groth16/verifier.rs#L32

skips the first entry of `pvk.ic`.  Because it is used to initialize `acc`, this has the effect that it is added into the sum with fixed coefficient 1.

The verification description in the spec doesn't mention anything about a fixed coefficient: 
![Screenshot from 2020-07-17 11-19-05](https://user-images.githubusercontent.com/44879/87818430-627b2380-c81f-11ea-9b6f-49f82741b444.png)

**Comment by swasilyev** [comment]
The first public input is reserved to be the scalar field unity, starting from original Gro16 article. It allows eg constants in linear combinations.

**Comment by daira** [comment]
The encodings of the public circuit inputs, including the fixed 1 element, are specified in Appendices A.4 and A.5. Granted this isn't obvious and there should be more cross-referencing (also, those sections aren't quite finished).

**Comment by hdevalence** [comment]
Thanks for the explanation -- should there be a note explaining this in the source? I'm happy to add one separately or as part of #253
