### ISSUE TITLE
bellman: remove deprecated and unmaintained futures_cpupool

### ISSUE THREAD

**Issue by hdevalence** [zcash/librustzcash#263]
`futures_cpupool` uses the old-style `0.1` futures that are no longer actively maintained and are not interoperable with the rest of the rust futures ecosystem.  It should be removed from `bellman`.

One option is to continue to use `std::future::Future` futures.  These require an executor.  One option is the threadpool from the [futures crate](https://docs.rs/futures/0.3.5/futures/executor/struct.ThreadPool.html), a simple executor which just handles CPU-bound work.  Another option is Tokio's [blocking threadpool](https://docs.rs/tokio/0.2.22/tokio/task/index.html#spawn_blocking).

Another option would be to deprecate the use of futures and use a synchronous API instead.

Not knowing more about the design of bellman it's hard for me to determine which of the two high-level options is the best.

**Comment by hdevalence** [comment]
Perhaps another option to consider is dropping the multicore / non-multi-core distinction in the bellman code, using Tokio's `spawn_blocking` unconditionally, and outsourcing the single/multi-threading configuration to the configuration of the [Tokio runtime](https://docs.rs/tokio/0.2.22/tokio/runtime/index.html#runtime-configurations).

**Comment by str4d** [comment]
Closed by https://github.com/zkcrypto/bellman/pull/69 (which backported the Filecoin changes to migrate `bellman` to `rayon`).
