### ISSUE TITLE
Fix lint warnings: "lint `intra_doc_link_resolution_failure` has been renamed to `broken_intra_doc_links`"

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#279]
GitHub Actions / Nightly lint

ff/src/lib.rs#L5 and group/src/lib.rs#L2 :
```
lint `intra_doc_link_resolution_failure` has been renamed to `broken_intra_doc_links`
```

**Comment by str4d** [comment]
Apparently this is expected in the lint renaming process: https://github.com/rust-lang/rust/pull/74926#issuecomment-668382103

The standard fix would be to apply `allow(unknown_lints)` until https://github.com/rust-lang/rust/pull/74430 is merged and we are on a stable release containing the stabilised lint.

**Comment by str4d** [comment]
We can rename the lints once our MSRV is 1.48.0.

**Comment by daira** [comment]
Rust 1.48.0 is nearly 3 months old; why not update the MSRV now? Those warnings really get in my way when reviewing.
