### ISSUE TITLE
Multi-asset extensions to Sapling

### ISSUE THREAD

**Issue by ghost** [zcash/librustzcash#299]
Hi all! Inspired by the [ZIP](https://github.com/str4d/zips/blob/zip-udas/drafts/zip-user-defined-assets.rst) for user defined assets, we have extended the demo a bit to be more complete, and may be found [here](https://github.com/metastatedev/librustzcash/tree/masp-zcash)

Since the circuit extensions are rather generic, hopefully they will be of broad interest.

Comments, criticism, feedback, and review are very welcome! (And I do expect some strong opinions ;) )

edit: Also, we are interested in potentially upstreaming some or all of the code, or otherwise contributing to the community

**Comment by nuttycom** [comment]
Subsumed by ZIP 226 https://zips.z.cash/zip-0226
