### ISSUE TITLE
When is 0.5.0 expected?

### ISSUE THREAD

**Issue by jsamol** [zcash/librustzcash#345]
Hi! 👋 

My team and I have been using librustzcash crates to develop [a Wasm library](https://github.com/airgap-it/airgap-sapling) which we can later use in our wallet. So, first of all, thank you guys for your hard work in making such a complex and useful project available to the community 😄 

We could really use a new release on the registry, though 😉 You see, at one point we needed some critical features that had been already implemented but not published yet (and still haven't been), so we switched our dependencies from the published crates to dependencies coming directly from this repository. Unfortunately, as one could expect, it's not stable and now every time we touch our code and the dependencies update to the latest, there's a high chance we have to update our code too as it's not fully compatible with the changes recently pushed to your `master` branch.

I don't know if there's something stopping you from publishing a new version (I can see on crates.io that it was updated 6 months ago for the last time) or nobody just hasn't needed it until now, but we would really appreciate if you provided us with a more stable way of getting the recent changes.

**Comment by str4d** [comment]
Hi! Thanks for reaching out 😄

The main blocker on getting a new release out has been engineering time 😅 (we've been busy with NU5 draft ZIP work and the `halo2` implementation). The current blocker was figuring out the performance issue in #334, which has not yet been resolved; I suspect we will just update the non-`ff` crates for now.

That leaves the path to 0.5.0 as:
- [ ] Update non-`ff` crates.
- [ ] Go over the current public APIs of the crates and check what they expose is what we expect.
- [ ] Make a pass over the issues for any fixes or last changes we should do.
- [ ] Verify that `zcashd` tests pass when built with these crates.
- [ ] Cut the releases!

I'll update this list if I think of anything else.

**Comment by str4d** [comment]
0.5.0 release is out!

**Comment by jsamol** [comment]
Perfect! Thanks for taking care of that and letting me know 😉
