### ISSUE TITLE
Add database migration support to zcash_client_sqlite

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#369]
At present the wallets have to handle migrations independently, and there is redundant effort between Android and IOS in terms of handling those migrations. In addition, we don't have any systematic process for supporting ecosystem partners when a migration is required.

Migrations should allow for interleaving of SQL and Rust code in a series of steps, where progress through those steps is tracked by data stored in the database. The migration process should use SQLite's support for transactional DDL. 

Related idea: once we have migration support, it might make sense to integrate an API for taking backups as well. Periodic database backups could make for an easy reset/restore mechanism.

**Comment by str4d** [comment]
I was doing some searching for a personal project, and came across two crates that might be helpful:
- https://crates.io/crates/barrel - Rust APIs for writing migrations.
- https://crates.io/crates/refinery - Migration runner that tracks migrations in a database table.

**Comment by str4d** [comment]
`refinery` uses the following table structure to track migrations (the table name itself can be configured but shouldn't be changed on the fly):
```sql
CREATE TABLE IF NOT EXISTS refinery_schema_history(
    version INT4 PRIMARY KEY,
    name VARCHAR(255),
    applied_on VARCHAR(255),
    checksum VARCHAR(255));
```

**Comment by nuttycom** [comment]
I really wish that there were https://hackage.haskell.org/package/dbmigrations for every language; it structures migrations as a DAG natively. However, for the wallets, linear migrations are probably enough, so barrel/refinery seems fine.

**Comment by str4d** [comment]
`barrel` is just a helper for writing the SQL parts of the migrations.

I did a bit more searching, and found https://crates.io/crates/schemer which _does_ implement a DAG.
