### ISSUE TITLE
Feature Request: Transaction Builder should report progress

### ISSUE THREAD

**Issue by adityapk00** [zcash/librustzcash#376]
Today, when users send transactions with large numbers of sapling notes, the transaction can take multiple minutes to build. Wallets should report progress to the user in this scenario, but current don't have access to how many SpendDescriptions and SaplingOutputs have been created so far. 

It would be cool if `zcash_primitives::transaction::Builder` can report progress. 

Maybe it could take a `mpsc::channel::Sender::<u32>` and send a message on the channel everytime some progress is made. 

Wallets can then listen on that channel and update the wallet UI.

**Comment by str4d** [comment]
Closed by #377 (modified in #388).
