### ISSUE TITLE
Migrate PRF^Expand domain to a common Zcash primitives crate

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#391]
```suggestion
/// The set of domains in which $PRF^\mathsf{expand}$ is defined.
/// This currently only includes domains used in Orchard.
/// TODO: refactor calls of $PRF^\mathsf{expand}$ for Sapling
/// to use this approach.
```

_Originally posted by @daira in https://github.com/zcash/orchard/pull/93#discussion_r641922460_

**Comment by str4d** [comment]
This would be _perfect_ to go in a crate of Zcash primitives, which is what `zcash_primitives` was sort-of intended as. It has in practice grown significantly, so while I'd like that to be where it ends up, in practice it needs to go somewhere that can live underneath the `orchard` crate. We should either pick some underlying crate we can use in the meantime (maybe `zcash_encoding`), or implement this after refactoring `zcash_primitives`.

**Comment by nuttycom** [comment]
This now lives in the `zcash_spec` crate.
