### ISSUE TITLE
Add Orchard support to `zcash_client_sqlite`

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#404]
We need the ability to track Orchard notes in the wallet, and spend them.

I think the simplest integration pathway is to add a `note_type` column to most tables, with a default of "Sapling" (to match current internals), and then we can use an "Orchard" type to separate notes. However, some tables might be quite Sapling-specific (I'm thinking in particular about `rcm`, which won't be a sufficient column for Orchard), where we need a new Orchard-specific table.

**Comment by nuttycom** [comment]
Closed by #1182, #1234, #1241, #1235, #1248, #1254, #1255, #1262
