### ISSUE TITLE
Add Orchard support to the transaction builder

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#406]
Now that the refactors are all done, we can integrate the modular Orchard bundle builder into our Rust transaction builder.

- [ ] The standard ZIP 317 fee algorithm applies to fully-constructed transactions. However, in the transaction builders, the Orchard (and potentially the Sapling) bundle may be padded to 2 actions. We need to ensure that this padding is taken into account by the ZIP 317 fee estimation code.

**Comment by nuttycom** [comment]
Resolved by #1065
