### ISSUE TITLE
FYI: Cannot use client_backend/primitives/proofs together anymore

### ISSUE THREAD

**Issue by hhanh00** [zcash/librustzcash#412]
Since commit `4efb21d1c7639a309fb43dc52dab921a685d3a94`

Does not work:
```
[dependencies.zcash_client_backend]
git = "https://github.com/zcash/librustzcash.git"
rev = "4efb21d1c7639a309fb43dc52dab921a685d3a94"

[dependencies.zcash_primitives]
git = "https://github.com/zcash/librustzcash.git"
rev = "4efb21d1c7639a309fb43dc52dab921a685d3a94"

[dependencies.zcash_proofs]
git = "https://github.com/zcash/librustzcash.git"
rev = "4efb21d1c7639a309fb43dc52dab921a685d3a94"
```

Works
```
[dependencies.zcash_client_backend]
git = "https://github.com/zcash/librustzcash.git"
rev = "35023ed8ca2fb1061e78fd740b640d4eefcc5edd"

[dependencies.zcash_primitives]
git = "https://github.com/zcash/librustzcash.git"
rev = "35023ed8ca2fb1061e78fd740b640d4eefcc5edd"

[dependencies.zcash_proofs]
git = "https://github.com/zcash/librustzcash.git"
rev = "35023ed8ca2fb1061e78fd740b640d4eefcc5edd"
```

There are version conflicts since the inclusion of orchard crates.

**Comment by pacu** [comment]
Thanks for reporting this. Would you mind posting any `cargo build` outputs?

**Comment by str4d** [comment]
This is an expected problem, as we've been focusing on the changes necessary to implement NU5 consensus rules in `zcashd`, and have not made any changes to the `zcash_client_*` crates. These are being tracked in #403 and #404.

**Comment by nuttycom** [comment]
The version conflicts that this is referring to are the `funty` conflicts. These are resolved in the current `master` branch of librustzcash.
