### ISSUE TITLE
zcash_address: Alter Unified Address encoding to support more typecodes and longer receivers

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#431]
Implement:
- https://github.com/zcash/zips/issues/548
- https://github.com/zcash/zips/issues/549
- https://github.com/zcash/zips/issues/550

**Comment by nuttycom** [comment]
The specification change is https://github.com/zcash/zips/pull/551

**Comment by str4d** [comment]
Implemented in #434.
