### ISSUE TITLE
Parameter loading fails when the filesystem encoding is not UTF-8

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#44]
Most Windows systems when using ANSI APIs, and some Unix systems, do not use UTF-8 encoding for filesystem paths. It's also common for usernames to have non-ASCII characters. In that case parameter loading will fail here: https://github.com/zcash/librustzcash/blob/041671f6425563bdef43c7c907a8396da76f8f21/librustzcash/src/rustzcash.rs#L144-L157

The comment is correct; we should not be using `CStr`, since `CStr::to_str` assumes UTF-8 (see doc just above [here](https://doc.rust-lang.org/std/ffi/struct.CStr.html#examples-6)).

Strictly speaking the Right Way to do it on Windows is to use "wide" (UTF-16) filesystem APIs. I don't know how well supported that is in Rust, and for now I'd recommend sticking to ANSI APIs and just passing the bytes through as-is.

**Comment by daira** [comment]
We have a lot of Russian and Chinese users, so this is going to crop up a lot. Note that it's a regression in recent versions of zcashd (post-1.1.2 I think), because this code was not previously used and the C++ code does handle non-ASCII filenames correctly.

**Comment by radix42** [comment]
yes it is post-1.1.2, 2.0.0 didn't build on Windows (because #reasons), so it didn't pop up until now

**Comment by ebfull** [comment]
My suggestion is to use `u8string()` when constructing `sapling_spend_str` etc. on the C++ side of things, so the Rust code can be unchanged and just assume UTF-8. Does this work?

**Comment by daira** [comment]
The Rust code can't be unchanged, because it calls `CStr::to_str` which assumes UTF-8.
