### ISSUE TITLE
`zcash_address`: Fix raw encoding representation

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#462]
ZIP 316 defines the raw encoding of a UA as the concatenation of the TLV-encoded receivers. This is unjumbled and without padding, and has no dependency on the network.

`zcash_address` defines a (fortunately crate-private) `unified::Address::to_bytes` method that is documented as returning the raw encoding. However, it appends padding and then outputs the jumbled data.

We should fix `unified::Address::to_bytes` to return the raw encoding, and then have a separate (also crate-private) method to return the jumbled encoding that is used within Bech32m. Then if we end up needing to expose the raw encoding at some later stage, it is the correct one.

**Comment by nuttycom** [comment]
On the principle of YAGNI, I'm going to say that this is done; if we need to expose the raw encoding as a function that returns bytes, we can add that later.
