### ISSUE TITLE
Is x-lookup enforced in lookup3_xy_with_conditional_negation?

### ISSUE THREAD

**Issue by fleupold** [zcash/librustzcash#47]
I might not be understanding the code correctly, but where are we enforcing that the x-coordinate is correctly selected from the lookup table, when doing a 3-bit lookup with conditional negation (e.g. used in `pedersen_hash`)?

https://github.com/zcash/librustzcash/blob/06da3b9ac8f278e5d4ae13088cf0a4c03d2c13f5/sapling-crypto/src/circuit/lookup.rs#L174-L192

I can only see the y-lookup being enforced. Does enforcement happen in `add_bool_with_coeff` (I couldn't find any `cs.enforce` in that method)? 
Or do we not need to verify the x-lookup for some reason?

**Comment by daira** [comment]
The x coordinate is a linear combination, so the x lookup doesn't need its own constraint. The constraints needed will be added when the linear combination is used.

**Comment by fleupold** [comment]
I see now, thank for clarifying!

An example of where the linear combination is used in an enforced constraint is addition of the montgomery points resulting from the lookup:

https://github.com/zcash/librustzcash/blob/e1c6232dd7a5368aa9342649d73db27522cc8d6e/sapling-crypto/src/circuit/ecc.rs#L688
