### ISSUE TITLE
Can pedersen_hash be point at infinity?

### ISSUE THREAD

**Issue by fleupold** [zcash/librustzcash#48]
Is it possible for `pedersen_hash` to return the point at infinity? If so how do we ensure that such results don't lead to hash collisions?

Let's assume we have a scalar `s` that spans two segments (let's assume `s` includes the 6 personalisation bits). Further let`s1 = s[0..63]` and `s2 = [63..-1]` be the two segments and `G1, G2` two prime order base points of the jubjub curve.

If I understand the code correctly, we compute `pedersen_hash(s) = s1 * G1 + s2 * G2`

It seems possible that this result could be the point at infinity.

In that case, if we e.g. shift `s1` and `s2` by one bit each, that is `s1' = s1 << 1` and `s2' = s2 << 1` and calculate `pedersen_hash(s')`, where `s' = concat(bin(s1), bin(s2))` we get:
```
pedersen_hash(s') = (s1 << 1) * G1 + (s2 << 1) * G2 
                  = 2*s1*G1 + 2*s2*G2 
                  = 2*(s1*G1 + s2*G2) 
                  = 2 * (INF) = INF = pedersen_hash(s)
```

which would be a collision, wouldn't it? 

I'm likely missing some basic understanding of why this is not possible or what we are doing to avoid this case, and would appreciate some insight. 

Thanks.

**Comment by str4d** [comment]
For a Pedersen hash defined over a generic elliptic curve, I think something like this might be possible, though you would need to account for the windowed encoding mechanism (it might be sufficient to just bit-shift by 3 bits instead of 1, but I haven't thought about it much).

However, `pedersen_hash` is defined over Jubjub, which is a twisted Edwards curve with `d` being a non-square. This means that addition is complete, and so there is no point at infinity.

(cc @daira because I've likely mis-explained _something_ 😅)

**Comment by daira** [comment]
The Pedersen hash is *defined* in terms of the Edwards curve, which as @str4d says has no point at infinity. The zero point has an affine representation (0, 1).

The output of the hash is the u-coordinate of the resulting Edwards point. This is 0 for the zero point, which is a possible output. (If you actually find an input that gives this output, you can also find collisions in the hash. Pedersen hashes are not the only kind of hash for which this is the case; for example if you find an input to SHA-256 that results in a zero output then you can also find collisions in SHA-256, although for a different reason.)

In the circuit, the hash is *implemented* in terms of *both* the Edwards curve and the birationally equivalent Montgomery curve. The use of the latter is carefully limited to avoid occurrence of the point at infinity and other exceptional cases; this is explained and justified in appendix A.3.3.9 of the protocol spec.
