### ISSUE TITLE
Wallet Import Format keys used by zcash_client_backend have the same lead byte (0x80) for mainnet and testnet

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#481]
https://github.com/zcash/librustzcash/pull/341 (which has been the deployed branch for `zcash_client_backend` since early 2021) uses an encoding based on Bitcoin's [Wallet Import Format](https://en.bitcoin.it/wiki/Wallet_import_format) for transparent private keys.

However, on encoding this implementation uses 0x80 as the lead byte of the Base58Check input for both mainnet and testnet; the Bitcoin wiki specifies 0xEF for testnet.

On decoding, the `zcash_client_backend` implementation [does not check](https://github.com/zcash/librustzcash/pull/341#discussion_r784365477) the lead byte (nor the trailing byte which should be 0x01, nor the length which should be 34 bytes).

According to [the Bitcoin wiki](https://en.bitcoin.it/wiki/Wallet_import_format#WIF_to_private_key), some implementations of WIF for Bitcoin used 0x81 to 0x87 inclusive as the lead byte, but there should be no such implementations for Zcash in the wild.

For compatibility we may need to accept a lead byte of 0x80 even when the key is for testnet. That is unfortunate, since a mainnet key being used on testnet is precisely the mistake we'd want to prevent. But at least it means that we can compatibly switch to encoding testnet keys with a lead byte of 0xEF, and reject those being used on mainnet.

Alternatively we could switch to using two distinct lead bytes outside the range {0x80 to 0x87, 0xEF} (say, 0x7F for mainnet and 0xEE for mainnet), to distinguish our keys from Bitcoin keys. The decoder would accept both 0x80 and the correct new lead byte for the network.

**Comment by str4d** [comment]
@nuttycom has altered the auto-shielding PR to only do the correct thing, but we still need to confirm that this is compatible with the mobile SDKs. I think the issues here are limited because it only affects testnet users, but if we decide to proceed with only merging the correct thing, we do need to document the problem for testnet mobile SDK users, and what its symptoms will look like.

**Comment by nuttycom** [comment]
We should actually get rid of WIF entirely; it doesn't carry the information that we need in order to derive change addresses or OVKs.

**Comment by nuttycom** [comment]
Fixed in a1e693d15f21afc191d70112eacd6a2c224f3305
