### ISSUE TITLE
Failing test?

### ISSUE THREAD

**Issue by dusty-phillips** [zcash/librustzcash#52]
I'm getting a test failure when running `cargo test uint32_shr`. Is this normal/expected, or do I have something odd in my configuration?

Here's the tail end of the traceback:

```
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: sapling_crypto::circuit::uint32::test::test_uint32_shr
             at sapling-crypto/src/circuit/uint32.rs:631
  10: sapling_crypto::__test::TESTS::{{closure}}
             at sapling-crypto/src/circuit/uint32.rs:624
  11: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  12: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:642
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
```

Some specs:
 *  rustc 1.29.2 (17a9dc751 2018-10-05)
 *  cargo 1.29.0 (524a578d7 2018-08-05)
 *  Fedora 28
 *  Linux Kernel 4.19.2

**Comment by ebfull** [comment]
Yeah, I need to use wrapping shifts in the test. It's just a bug in the test. I recommend running tests with `--release` anyway because otherwise I think they'll be incredibly slow.
