### ISSUE TITLE
Upstream `hdwallet` changes

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#521]

**Comment by nuttycom** [comment]
This will be resolved by https://github.com/jjyr/hdwallet/pull/16

**Comment by str4d** [comment]
Per https://github.com/zcash/librustzcash/pull/523#discussion_r844502618, we need to ensure that the commit used by `zcashd 4.7.0` **DOES NOT** disappear, ideally by ensuring that the upstream PR is merged as-is without any rebasing.

**Comment by str4d** [comment]
Closed by #552.
