### ISSUE TITLE
using Jubjub crate 

### ISSUE THREAD

**Issue by omershlo** [zcash/librustzcash#58]
Hi, 
 I want to use the crate Jubjub in your workspace in my Rust project. 
Do you know what I should specify in my Cargo.toml?

**Comment by str4d** [comment]
You need to import the `sapling-crypto` crate like so:

```
[dependencies.sapling-crypto]
git = "https://github.com/zcash/librustzcash.git"
rev = "06da3b9ac8f278e5d4ae13088cf0a4c03d2c13f5"
```

And then you can `use sapling_crypto::jubjub` in your project.
