### ISSUE TITLE
`zcash_client_backend`: Add `add_new_account` to the data access API.

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#628]
At present it's possible to initialize the accounts table with some number of account/key pairs, but we don't actually have an API to add am account after the initial setup.

**Comment by AArnott** [comment]
Maybe not... considering it doesn't let me add an account with a particular index. It also doesn't support adding by UVK.

**Comment by AArnott** [comment]
This should be closed by https://github.com/zcash/librustzcash/pull/1425
