### ISSUE TITLE
Bring fork of blake2_rfc in as a git subtree

### ISSUE THREAD

**Issue by ebfull** [zcash/librustzcash#67]
We do this for other stuff, and I think this should be no exception. It avoids me having to check hashes in [PRs like this](https://github.com/zcash/librustzcash/blob/3d39706aeeb8a1e56b65192b02c1a437796191d9/zcash_proofs/Cargo.toml#L16).

**Comment by str4d** [comment]
The more likely alternative avenue is to switch to the `blake2` crate once https://github.com/RustCrypto/hashes/pull/78 is merged (which I ported from our fork of `blake2_rfc`).
