### ISSUE TITLE
Fee calculation doesn't take airity-padding-to-two into account

### ISSUE THREAD

**Issue by AloeareV** [zcash/librustzcash#709]
The sapling builder adds dummy outputs until there are a minimum of 2 as long as there's at least one input. This isn't taken into account in the transaction builder's fee calculations.

**Comment by AloeareV** [comment]
Fixed by #710

**Comment by str4d** [comment]
The fix in #710 is incomplete, as `Builder::build_zfuture` needs the same fix. I'll open another PR that addresses this.
