### ISSUE TITLE
Break up any unnecessary data dependencies in `zcash_client_sqlite`

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#713]
We should determine how coupled the current database format of `zcash_client_sqlite` is to per-block data persistence, and if necessary create migrations that separate out the various components (to allow them to be updated independently). This will also help to inform the API changes in #712.

**Comment by str4d** [comment]
Here is AFAICT the data dependency graph for the current `zcash_client_sqlite` format. Formatting notes:
- Subgraphs show common fields that must all be collectively present (i.e. `NOT NULL` fields). Standalone nodes are nullable columns.
- Solid edges show required dependencies (all dependencies must be present in the database for the dependent field to be present). Dotted lines show optional dependencies.

```mermaid
graph RL;

subgraph accounts
accounts_account[ID];
accounts_ufvk[UFVK];
end

subgraph addresses
addresses_di_be[Diversifier idx]
addresses_address[Address]
end

subgraph blocks
blocks_height[Height];
blocks_hash[Hash];
blocks_time[Time];
blocks_sapling_root[Sapling tree root];
end

subgraph transactions
transactions_ref[Tx ref]
transactions_txid[TxId]
end

transactions_created[Created]
transactions_tx_index[Tx index]
transactions_expiry_height[Expiry height]
transactions_raw[Raw tx]
transactions_fee[Fee]

subgraph received
received_ref[Note ref]
received_output_index[Output idx]
received_diversifier[d]
received_value[Value]
received_rcm[rcm]
received_nf[nf]
received_is_change[Is change?]
end

received_memo[Memo]
received_spent[Is spent?]

subgraph witnesses
witnesses_ref[Ref]
witnesses_witness[Witness]
end

subgraph sent
sent_ref[Sent note]
sent_output_pool[Output pool]
sent_output_index[Output idx]
sent_value[Value]
end

sent_to_address[To addr]
sent_to_account[To account]
sent_memo[Memo]

subgraph utxos
utxos_ref[UTXO]
utxos_address[Address]
utxos_prevout_txid[Prevout TxId]
utxos_prevout_idx[Prevout idx]
utxos_script[Script]
utxos_value_zat[Value]
utxos_height[Height]
end

utxos_spent_in_tx[Spent]

addresses_address --> accounts_account

transactions_ref -.-> blocks_height

transactions_created --> transactions_ref
transactions_tx_index --> transactions_ref
transactions_expiry_height --> transactions_ref
transactions_raw --> transactions_ref
transactions_fee --> transactions_ref

received_ref --> accounts_account
received_ref --> transactions_ref

received_memo --> received_ref
received_spent --> transactions_ref
received_spent --> received_ref

witnesses_ref --> received_ref
witnesses_ref --> blocks_height

sent_ref --> accounts_account
sent_ref --> transactions_ref

sent_to_address --> sent_ref
sent_to_account --> accounts_account
sent_to_account --> sent_ref
sent_memo --> sent_ref

utxos_ref --> accounts_account
utxos_spent_in_tx --> utxos_ref
utxos_spent_in_tx --> transactions_ref
```

**Comment by str4d** [comment]
WIP diagram of a potential restructuring of the data dependencies:
```mermaid
graph BT;

subgraph accounts
accounts_account[ID];
accounts_ufvk[UFVK];
end

subgraph addresses
addresses_di_be[Diversifier idx]
addresses_address[Address]
end

subgraph blocks
blocks_height[Height];
blocks_hash[Hash];
blocks_time[Time];
blocks_sapling_root[Sapling tree root];
end

transactions_txid[TxId]
transactions_tx_index[Tx index]

transactions_ref[Tx ref]

transactions_created[Created]
transactions_expiry_height[Expiry height]
transactions_raw[Raw tx]
transactions_fee[Fee]

subgraph received
received_ref[Note ref]
received_output_index[Output idx]
received_diversifier[d]
received_value[Value]
received_rcm[rcm]
received_nf[nf]
received_is_change[Is change?]
end

received_memo[Memo]
received_spent[Is spent?]

subgraph witnesses
witnesses_ref[Ref]
witnesses_witness[Witness]
end

subgraph sent
sent_ref[Sent note]
sent_output_pool[Output pool]
sent_output_index[Output idx]
sent_value[Value]
end

sent_to_address[To addr]
sent_to_account[To account]
sent_memo[Memo]

subgraph utxos
utxos_ref[UTXO]
utxos_address[Address]
utxos_prevout_txid[Prevout TxId]
utxos_prevout_idx[Prevout idx]
utxos_script[Script]
utxos_value_zat[Value]
utxos_height[Height]
end

utxos_spent_in_tx[Spent]

addresses_address --> accounts_account

transactions_tx_index --> blocks_height

transactions_ref -.-> transactions_txid
transactions_ref -.-> transactions_tx_index

transactions_created --> transactions_ref
transactions_expiry_height --> transactions_ref
transactions_raw --> transactions_ref
transactions_fee --> transactions_ref

received_ref --> accounts_account
received_ref --> transactions_ref

received_memo --> received_ref
received_spent --> transactions_ref
received_spent --> received_ref

witnesses_ref --> received_ref
witnesses_ref --> blocks_height

sent_ref --> accounts_account
sent_ref --> transactions_ref

sent_to_address --> sent_ref
sent_to_account --> accounts_account
sent_to_account --> sent_ref
sent_memo --> sent_ref

utxos_ref --> accounts_account
utxos_spent_in_tx --> utxos_ref
utxos_spent_in_tx --> transactions_ref
```

**Comment by str4d** [comment]
@nuttycom and I discussed this in a pairing today. There are several core issues that need addressing:
- The `blocks` table is assumed to be contiguous; its maximum `height` encodes the metadata of "where are we fully synced to?"

DAGSync necessitates that we store data non-contiguously. We agreed that this should be done at the granularity of blocks; then for blocks that are at least 100 back from the chain tip, we can simply refer to heights. I noted that we can store this data as a table of "ranges that have not yet been scanned", with two columns `start_height` and `end_height`. This makes state management simple:
- When starting up, we `SELECT` the entire table, and pass those ranges to the DAGSync engine.
- When a block has been fully scanned, we atomically:
  - `SELECT * FROM table WHERE start_height <= height_of_synced_block AND height_of_synced_block < end_height` (which should only return at most one result) to obtain the row representing the range `[start_height..end_height]`
  - Delete that row from the table.
  - Insert two new rows for the ranges `[start_height..height_of_synced_block]` and `[height_of_synced_block + 1..end_height]`.
- The insertion can be batched for recording that multiple blocks have been fully synced.
- If the DAGSync engine is killed before a block is fully synced (e.g. we've trial-decrypted some of a block's transactions but not all of them), then on restart we will do a small amount of duplicate work.

**Comment by nuttycom** [comment]
We've done everything we need to do here for #730; anything additional that is required for #720 will be tracked in a new issue once we figure out what that is.
