### ISSUE TITLE
Document behaviour of the "pending transactions" databases in the Android and iOS mobile SDKs

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#714]
The Android and iOS mobile SDKs have their own databases tracking transactions that they are in the process of creating. We want to move this into `zcash_client_sqlite` (either directly, or as part of the two phase propose-commit API change), so we need to understand what the current behaviour is.

**Comment by nuttycom** [comment]
@pacu described the pending transactions database as follows:

> The pending transaction database contains a record of the attempt of sending a signed (encoded) transaction. It stores the transaction’s raw bytes and accessory information like submit attempts, error information, expiry height and a nullable minedHeight field among others. The transactions inside the pending_transactions table (and database) prevail until a transaction shows up in the blockchain and we pick it up when scanning and decrypting (enhancing). At that time, the pending transaction is kept in the database until the block height of the chain is greater than the mined height + number of confirmations . At that point in time the transaction is no longer considered pending and it can be flushed from the pending database.

> In the case of a reorg that’s less than 10 blocks the sdk will rewind the databases and the pending db information will prevail. This is how the wallet can show the user that this transaction is still pending and handle any changes that the reorg caused.  The reorg might also cause that the transaction is never mined so the pending db can also support that scenario. The AdvanceReOrg tests of the iOS SDK cover these scenarios by replaying them with darksidewalletd.
