### ISSUE TITLE
Expose transaction proposal via the `zcash_client_backend` API

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#716]
https://github.com/zcash/librustzcash/pull/689 added a "proposed" transaction state, that represents the transaction after note selection, fee calculation, and output determination (including change), have been performed but prior to the proving and signing operations that are required before the transaction can be sent for inclusion into the chain.

This state needs to be exposed to the wallet API in order to display fees and transaction privacy implications to the user. The current `spend` function performs all these steps at once, but it can be usefully broken down into separate stages.

**Comment by str4d** [comment]
Closed by #761.
