### ISSUE TITLE
Extract "scan arbitrary block range" function from `scan_cached_blocks`

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#728]
`scan_cached_blocks` has a specific interaction pattern with other chain scanning functions like `validate_chain`, and is built around an assumption of linear scanning. For DAGSync we want to be able to perform "random-access scanning", with the ability to handle contiguous batches of blocks (to optimise network access patterns and note commitment tree update patterns).

As a stepping stone towards this, we want to enable scanning the last 100 blocks as a batch (this being the section of the chain that can encounter reorgs during steady state operations). Rather than expanding or adapting `scan_cached_blocks` for this purpose, we should extract a new function that can perform this operation.

This may or may not be reusable for DAGSync itself (where we will be using a `BatchScanner` that processes more than just a contiguous batch), but we can adapt it at that point (vs `scan_cached_blocks` which should have its semantics preserved until we can remove it entirely).

**Comment by nuttycom** [comment]
This was completed by the changes in #831 and #872
