### ISSUE TITLE
Add range-based note commitment trees to the light client

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#729]
Once https://github.com/zcash/incrementalmerkletree/issues/48 is complete, we want to integrate it into `zcash_client_backend` and `zcash_client_sqlite` as a component of DAGSync. As a stepping stone towards this, we should integrate it into the `zcash_client_sqlite` datastore, and then when new notes are discovered as part of `scan_cached_blocks`, we add them to the new tree. The new tree can then be updated independently of both the existing witnesses and subsequent `scan_cached_blocks` calls (and perhaps we even leave the existing witness update logic in place initially for minimal disruption).

**Comment by nuttycom** [comment]
Closed by #831
