### ISSUE TITLE
Enable fast-update of witness data for existing notes (Spend-before-Sync)

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#730]
This is an intermediate step on the way to a full DAGSync architecture. This issue can be closed when we have wallet datastores and APIs that can enable existing notes to be made spendable without calling `scan_cached_blocks`. The workflow will be something like:
- Record new-style tree data for new notes.
- Roll this tree data forward via range updates of historic tree data.
- Scan the last 100 blocks (or last 2^16 tree or whatever) to fill in the remainder.

**Comment by nuttycom** [comment]
I've added https://github.com/zcash/librustzcash/issues/404 as a blocker for this ticket because even if we don't complete `orchard` integration as part of this ticket, we need to do all of the conceptual work for how to support Orchard in the data access API at the same time.

**Comment by nuttycom** [comment]
Closing as complete.
