### ISSUE TITLE
FsBlockDb - "no such table: compactblocks_meta"

### ISSUE THREAD

**Issue by pacu** [zcash/librustzcash#748]
````
Failed to write block metadata to FsBlockDb: Db(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such table: compactblocks_meta\")))"
````

when writing a block to the FsBlockDb the database file exists at the cache directory but its size is zero bytes. It's not being initialized with the corresponding table even though the documentation implies so 

````
impl FsBlockDb {
    /// Creates a filesystem-backed block store at the given path.
    ///
    /// This will construct or open a SQLite database at the path
    /// `<fsblockdb_root>/blockmeta.sqlite` and will ensure that a directory exists at
    /// `<fsblockdb_root>/blocks` where this block store will expect to find serialized block
    /// files as described for [`FsBlockDb`].
    pub fn for_path<P: AsRef<Path>>(fsblockdb_root: P) -> Result<Self, FsBlockDbError> {
````

**Comment by str4d** [comment]
This is a documentation bug. `FsBlockDb::for_path` ensures that the SQLite database file exists, but you need to separately call `zcash_client_sqlite::chain::init::init_blockmeta_db` to ensure that the database exists. See https://github.com/zcash/zcash-android-wallet-sdk/pull/736/files#diff-ea14a0f1195cb3440fbdf0cfba825a92078a0d1ff9655232f182000d360e2976R135-R157 for an example.

We _could_ call `init_blockmeta_db` internally but I'm guessing @nuttycom didn't do that to allow wallets to avoid calling it on hot paths (instead only calling `init_blockmeta_db` on startup). So we should instead expand the documentation of `FsBlockDb` to explain this.
