### ISSUE TITLE
zcash_proofs: Extract separate provers from `SaplingProvingContext`

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#752]
Currently, we have a single `SaplingProvingContext` which we initialize, use to create each Spend and Output proof (along with extra fields for the Spend description), and then call `binding_sig` to produce `bindingSig`. The reason for this workflow was that there is a data dependency on the entire transaction to create it. However, this data dependency is only a blocker on creating `bindingSig` due to computing `bsk`; the remaining components can be created independently of the whole transaction.

We should extract the per-proof creation logic from `SaplingProvingContext`, so they can be run independently.

**Comment by daira** [comment]
This was indeed closed by #1001, because #741 can be completed by #1023.
