### ISSUE TITLE
Payment disclosures

### ISSUE THREAD

**Issue by MeerKatDev** [zcash/librustzcash#758]
Hello, I'm one of the developers which will be involved in [this RFP](https://forum.zcashcommunity.com/t/zcash-uniffi-library-rfp/43468) involving this library. We're planning the development roadmap and I can't seem to find support for [payment disclosures](https://github.com/zcash/zcash/blob/master/doc/payment-disclosure.md) in here, is there a plan to include it in this library?

**Comment by str4d** [comment]
The payment disclosure document you referenced is Sprout-only, and essentially deprecated at this point; it is not and will not be supported in these crates, as we don't support creating Sprout transactions.

Payment disclosures as a general feature are something we _do_ intend to implement and support. They are blocked on finishing [ZIP 311](https://github.com/zcash/zips/pull/426) (and extending that draft from Sapling-only to properly include transparent and Orchard details), so currently there is no implementation.

**Comment by MeerKatDev** [comment]
We would like to support this feature for the RFP, if implemented in time (in the next ~3 months), and we're eager to help on it, if you let us. If you think though that it will take a much longer timespan to define the ZIP I will have to remove this feature from the list of the supported features.
