### ISSUE TITLE
Extract "component" crates into a separate repository

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#768]
Due to the `orchard` crate living in a separate repository, we currently have an annoying cyclic dependency between the two repositories, due to `zcash_primitives` depending on `orchard`, which depends on `zcash_note_encryption`. We also intend to move the Sapling protocol logic out into its own repository again (#738).

To improve development interactions between the crates, we should extract the "component crates" into a separate repository and Cargo workspace. By "component crates" I mean "crates that don't depend on the protocols", but this could also be the narrower "crates that the protocols depend on".

**Comment by str4d** [comment]
Here is the current dependency graph between the Rust crates:
```mermaid
graph TD
	n150[equihash]
	n151[f4jumble]
	n230[orchard]
	n232[zcash_note_encryption]
	n336[zcash_address]
	n337[zcash_encoding]
	n338[zcash_client_backend]
	n339[zcash_primitives]
	n340[zcash_proofs]
	n341[zcash_client_sqlite]

	n341 --> n338
	n341 --> n339
	n338 --> n230
	n338 --> n336
	n338 --> n337
	n338 --> n232
	n338 --> n339
	n338 --> n340
	n340 --> n339
	n339 --> n150
	n339 --> n230
	n339 --> n336
	n339 --> n337
	n339 --> n232
	n230 --> n232
	n336 --> n151
	n336 --> n337
```

If we define "component crates" as "crates that don't depend on the protocols" then we get this split:
```mermaid
graph TD
	subgraph components
	n150[equihash]
	n151[f4jumble]
	n232[zcash_note_encryption]
	n337[zcash_encoding]
	end

	subgraph protocols
	n230[orchard]
	end

	subgraph main
	n336[zcash_address]
	n338[zcash_client_backend]
	n339[zcash_primitives]
	n340[zcash_proofs]
	n341[zcash_client_sqlite]
	end

	n341 --> n338
	n341 --> n339
	n338 --> n230
	n338 --> n336
	n338 --> n337
	n338 --> n232
	n338 --> n339
	n338 --> n340
	n340 --> n339
	n339 --> n150
	n339 --> n230
	n339 --> n336
	n339 --> n337
	n339 --> n232
	n230 --> n232
	n336 --> n151
	n336 --> n337
```

If we define "component crates" as "crates that the protocols depend on" then we get this split:
```mermaid
graph TD
	subgraph components
	n232[zcash_note_encryption]
	end

	subgraph protocols
	n230[orchard]
	end

	subgraph main
	n150[equihash]
	n151[f4jumble]
	n337[zcash_encoding]
	n336[zcash_address]
	n338[zcash_client_backend]
	n339[zcash_primitives]
	n340[zcash_proofs]
	n341[zcash_client_sqlite]
	end

	n341 --> n338
	n341 --> n339
	n338 --> n230
	n338 --> n336
	n338 --> n337
	n338 --> n232
	n338 --> n339
	n338 --> n340
	n340 --> n339
	n339 --> n150
	n339 --> n230
	n339 --> n336
	n339 --> n337
	n339 --> n232
	n230 --> n232
	n336 --> n151
	n336 --> n337
```

**Comment by str4d** [comment]
Here is how I think I'd like the dependency graph to look after #738 (removing a few of the direct dependencies that can be represented via transitive paths for clarity):
```mermaid
graph TD
	subgraph components
	n232[zcash_note_encryption]
	n150[equihash]
	n151[f4jumble]
	n337[zcash_encoding]
	end

	subgraph protocols
	sapling[sapling-crypto]
	n230[orchard]
	end

	subgraph main
	n336[zcash_address]
	n338[zcash_client_backend]
	n339[zcash_primitives]
	n340[zcash_proofs]
	n341[zcash_client_sqlite]
	end

	n341 --> n338
	n338 --> n339
	n338 --> n340
	n340 --> n339
	n339 --> n150
	n339 --> sapling
	n339 --> n230
	n339 --> n336
	n339 --> n337
	sapling --> n232
	n230 --> n232
	n336 --> n151
	n336 --> n337
```

**Comment by nathan-at-least** [comment]
I came to this issue tracker to ask what defines `./components` crates and suggest documenting the distinction in the README. If we're splitting them out into a distinct workspace repo, can I request the README for that new repo clarifies the category.

Is it a correct definition for @str4d's [preferred grouping](https://github.com/zcash/librustzcash/issues/768#issuecomment-1409370272) that "components are crates which do not depend on Zcash protocols"?

Another way to think of the definition is what can you build with each set of crates. For the preferred layout is this accurate:

- `main` - Zcash MainNet clients/wallets/infra
- `protocols` - Zcash protocols in other systems beyond Zcash MainNet
- `components` - a broader set of applications / grab bag of utilities useful to the other two but not specific to them

**Comment by str4d** [comment]
So maybe this is the split to go for:
```mermaid
graph TD
	subgraph standalone_components
	nEqH[equihash]
	nF4J[f4jumble]
	end

	subgraph protocol_components
	nZEnc[zcash_encoding]
	nZNE[zcash_note_encryption]
	end

	subgraph protocols
	sapling[sapling-crypto]
	orchard[orchard]
	end

	subgraph main
	nZAddr[zcash_address]
	nZPrim[zcash_primitives]
	nZProof[zcash_proofs]
	nZCB[zcash_client_backend]
	nZCS[zcash_client_sqlite]
	end

	nZCS --> nZCB
	nZCB --> nZPrim
	nZCB --> nZProof
	nZProof --> nZPrim
	nZPrim --> nEqH
	nZPrim --> sapling
	nZPrim --> orchard
	nZPrim --> nZAddr
	nZPrim --> nZEnc
	sapling --> nZNE
	orchard --> nZNE
	nZAddr --> nF4J
	nZAddr --> nZEnc
```

**Comment by str4d** [comment]
Consider also that `zcash_proofs` is basically just the Sprout and Sapling circuits, extracted so that people could depend on `zcash_primitives` without depending on the circuit code. However, the use cases for that split were hardware wallets, none of which have gone in the direction of depending on `zcash_primitives`. We also now have `orchard` which requires that we depend on the circuit code.

Given that #738 will end up moving the Sapling circuit logic out of `zcash_proofs`, that would leave it only containing the Sprout circuit. So we could get rid of `zcash_proofs` entirely by moving the Sprout circuit into its own protocol crate, and then `zcash_proofs` is either completely vestigial, or only contains the logic for loading the relevant Zcash parameter files from disk:
```mermaid
graph TD
	subgraph standalone_components
	nEqH[equihash]
	nF4J[f4jumble]
	end

	subgraph protocol_components
	nZEnc[zcash_encoding]
	nZNE[zcash_note_encryption]
	end

	subgraph protocols
	sprout[sprout]
	sapling[sapling-crypto]
	orchard[orchard]
	end

	subgraph main
	nZAddr[zcash_address]
	nZPrim[zcash_primitives]
	nZProof[zcash_proofs]
	nZCB[zcash_client_backend]
	nZCS[zcash_client_sqlite]
	end

	nZCS --> nZCB
	nZCB --> nZPrim
	nZProof --> nZPrim
	nZPrim --> nEqH
	nZPrim --> sprout
	nZPrim --> sapling
	nZPrim --> orchard
	nZPrim --> nZAddr
	nZPrim --> nZEnc
	sapling --> nZNE
	orchard --> nZNE
	nZAddr --> nF4J
	nZAddr --> nZEnc
```
Then `zcash_primitives` itself becomes ripe for refactoring, in particular to take the key tree logic that is currently spread between it and `zcash_client_backend` and move that into a separate crate that depends on `zcash_address` (as it would be providing a concrete instantiation of the key tree logic, rather than the "bring your own backend" approach of `zcash_address`).

**Comment by str4d** [comment]
In #1041 we moved `zcash_note_encryption` into its own crate, so I think the pattern going forward is likely to be that for protocol components we just create standalone repositories.

**Comment by nuttycom** [comment]
#1140, #1142 and #1143 are intended to produce this result: 

```mermaid
graph TD
	subgraph standalone_components
	nEqH[equihash]
	nF4J[f4jumble]
	end

	subgraph protocol_components
	nZEnc[zcash_encoding]
	nZNE[zcash_note_encryption]
	end

	subgraph protocols
	sprout[sprout]
	sapling[sapling-crypto]
	orchard[orchard]
	end

	subgraph main
	nZAddr[zcash_address]
	nZPrim[zcash_primitives]
	nZProof[zcash_proofs]
	nZCB[zcash_client_backend]
	nZCS[zcash_client_sqlite]
	nZProto[zcash_protocol]
	nZMemos[zcash_memos]
	nZip321[zip321]
	end

	nZCS --> nZCB
	nZCB --> nZPrim
	nZProof --> nZPrim
	nZPrim --> nZProto
	nZCB --> nZip321
	nZip321 --> nZMemos
	nZip321 --> nZAddr
	nZip321 --> nZProto
	nZPrim --> nEqH
	nZPrim --> sprout
	nZPrim --> sapling
	nZPrim --> orchard
	nZPrim --> nZEnc
	sapling --> nZNE
	orchard --> nZNE
	nZAddr --> nF4J
	nZAddr --> nZEnc
```

**Comment by nuttycom** [comment]
This is now in an acceptable state; we no longer have circular dependencies that result in cycles in the repository graph.
