### ISSUE TITLE
`zcash_proofs`: Theoretical possibility of overflow leading to panic

### ISSUE THREAD

**Issue by mpguerra** [zcash/librustzcash#786]
As part of the zebra audit the following potential issue has been highlighted:

> In [src/hashreader.rs](https://github.com/zcash/librustzcash/blob/zcash_proofs-0.8.0/zcash_proofs/src/hashreader.rs#L14), a streamed hashing structure is defined, which hashes bytes (with the BLAKE2b hash function) as they flow, but also keeps track of how many bytes have been processed so far; the `byte_count` field maintains that information, and has type `usize` :

https://github.com/zcash/librustzcash/blob/ccb0444b6d799313604163738091e9c0ca94cf2a/zcash_proofs/src/hashreader.rs#L10-L15

> On 32-bit architectures, `usize` has size 32 bits, and thus any inputs larger than about 4.29 gigabytes will overflow that counter. In particular, the addition on [line 51](https://github.com/zcash/librustzcash/blob/ccb0444b6d799313604163738091e9c0ca94cf2a/zcash_proofs/src/hashreader.rs#L51) may then trigger a panic (if the code was compiled in debug mode), or silently truncate the count to its low 32 bits (if compilation used release mode). This issue cannot be triggered with the implementation in its current state, since hashing is performed only on files whose size has been explicitly verified to match the expected size for parameter files, with a maximum of about 0.73 gigabytes (for Sprout Groth16 parameters). Defining `byte_count` to have type `u64` would make the implementation more robust with regard to future development and protocol versions.

**Comment by str4d** [comment]
I looked into this again during the 0.11 release process, and the only effect in release mode of this would be that error messages report incorrect byte counts.
