### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by upbqdn** [zcash/librustzcash#804]
Commit https://github.com/zcash/librustzcash/commit/4fea57dcac77870a142f15b1f1dfa6d34a0de7b8 seems to introduce a regression that causes the compilation to fail with a bunch of errors similar to:

```
error[E0277]: the trait bound `String: tracing::Value` is not satisfied
   --> /.../.cargo/registry/src/github.com-1ecc6299db9ec823/halo2_proofs-0.3.0/src/dev/tfp.rs:431:13
    |
431 |             debug!(target: "assign_fixed", name = annotation, column = ?column, row = row);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tracing::Value` is not implemented for `String`
    |
    = help: the following implementations were found:
              <str as tracing::Value>
    = note: required for the cast to the object type `dyn tracing::Value`
    = note: this error originates in the macro `$crate::valueset` (in Nightly builds, run with -Z macro-backtrace for more info)
```

My guess is that `librustzcash` is trying to compile `halo2_proofs` with Rust 1.60, but `halo2_proofs` is for 1.59.

**Comment by str4d** [comment]
Can you retry with latest `main`? I am unable to reproduce this issue when compiling with our workspace MSRV of 1.60.

**Comment by upbqdn** [comment]
I can't reproduce this either anymore. Closing.

**Comment by upbqdn** [comment]
I can't reproduce this either anymore. Closing.
