### ISSUE TITLE
Add `data_api` methods that return scan progress metrics in terms of the number scanned notes.

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#865]
With the addition of note commitment tree sizes to compact block metadata, it will be possible for wallets to provide substantially more accurate progress information by reporting the number of notes scanned compared to the total number of notes in the chain since the wallet's birthday.

**Comment by zookozcash** [comment]
This is a feature request from the Zashi UI/UX design. I need to ask you “What's the percentage progress _since the earliest block that we haven't fully scanned_?”. I also need to ask “What was the date of that block?”

**Comment by nuttycom** [comment]
Tentative design to satisfy @zookozcash's requirement: https://github.com/zcash/librustzcash/pull/914/commits/d774275a2057c4dfad4a8b3cf83bc155a2639c7a#diff-7f82231afa857f8e7562f9184e551564997e1f74aaad9c6ba17e348fc89abeadR132
