### ISSUE TITLE
Behaviour of `{put,insert}_sent_output` for `memo == Some(MemoBytes::empty())` is confusing

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#866]
The internal functions `put_sent_output` (used in `store_decrypted_tx`) and `insert_sent_output` (used in `store_sent_tx`) have irregular behaviour when they are passed an output with a memo of `Some(MemoBytes::empty())`, as discussed in the thread at https://github.com/zcash/librustzcash/pull/857#discussion_r1224660086 . They would normally overwrite the existing entry when `output.memo() == Some(new_memo)`, but will not if `new_memo` is `MemoBytes::empty()`.

@nuttycom says [here](https://github.com/zcash/librustzcash/pull/857/files#r1232770977) that "Under normal circumstances the memo value for an output should never change between calls." But the behaviour is still irregular and error-prone.

**Comment by nuttycom** [comment]
I believe that this is now fixed in #886
