### ISSUE TITLE
zcash_client_backend: Add an "account birthday" parameter to the `create_account` API.

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#901]
As part of this implementation, the `init_blocks_table` and `init_accounts_table` APIs should be removed in favor of initialization using the normal methods of the data access API, `add_account` and `update_chain_tip`. By performing these removals, we can then establish the invariant that the `blocks` table only contains entries for blocks that the wallet has scanned, which will be a useful property.

**Comment by str4d** [comment]
This issue will need to result in an additional error state indicating that the caller needs to first call `update_chain_tip` so that newly-created accounts can have birthdays assigned to them (as opposed to `ScanRequired` which indicates the caller needs to call `suggest_scan_ranges`).

**Comment by nuttycom** [comment]
Fixed by #907
