### ISSUE TITLE
zcash_client_backend: tell me whether I can send a message (memo) to this UAddress

### ISSUE THREAD

**Issue by zookozcash** [zcash/librustzcash#910]
This is a feature request from the Zashi UI/UX design.

I need to give you a Unified Address, and you tell me if I'll be able to send a message (memo) to that address.

**Comment by nuttycom** [comment]
How about a function that says both whether we can send a memo, and whether we can send value? 3 possible results: (1) No, (2) Can send value, (3) Can send memo (and value).

**Comment by LukasKorba** [comment]
@nuttycom iOS already has implemented logic that memo is possible to add only if the address is valid one and not a transparent one. Seems like the reality is much more complex, can you please clarify why this condition is not enough? 

```swift
        public var isMemoInputEnabled: Bool {
            transactionAddressInputState.isValidAddress && !transactionAddressInputState.isValidTransparentAddress
        }
```

**Comment by nuttycom** [comment]
@LukasKorba that existing logic seems fine to me. I don't know how or why it would be more complex.

**Comment by nuttycom** [comment]
@zookozcash Once we add Orchard support to `zcash_client_backend` this requirement will be implicitly satisfied, because then by definition if you have a Unified Address you'll always be able to send a memo to the recipient, since Unified Addresses must always contain a shielded receiver.

**Comment by nuttycom** [comment]
Something else that occurs to me: a use case that I've seen requested several times by wallet developers is "give me the option to prohibit cross-pool (amount-revealing) transfers. If the API makes it possible to control this, then whether or not it's possible for a particular wallet to send a memo to a given uaddr may then depend upon whether cross-pool transfers are forbidden and whether the user's wallet has sufficient notes in the appropriate pool to perform the transfer.

**Comment by nuttycom** [comment]
Implemented in https://github.com/zcash/librustzcash/blob/01552bd65a881a6a1156098708a93d805a263867/components/zcash_address/src/lib.rs#L283-L291
