### ISSUE TITLE
sent_notes table is not fully populated after a recovery from seed

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#936]
This is separated out of #899 since it is a better-understood issue, and can be reproduced by the test in #908.

When a wallet is recovered from seed and fully rescanned, the `sent_notes` table does not contain all of the notes that were in that table before the recovery.

**Comment by nuttycom** [comment]
This issue is being deferred until after the SDK 2.0.0 release. It's safe to defer this issue because the process of "enhancing" the compact transaction data, which is standard in the mobile wallets, fills in the missing information in the `sent_notes` table.

**Comment by nuttycom** [comment]
This may be fixed by #1306
