### ISSUE TITLE
zcash_client_sqlite: Fix off-by-one in scan estimation start height

### ISSUE THREAD

**Issue by nuttycom** [zcash/librustzcash#945]
> Nit: now that `start_height = birthday_height` there's an off-by-one here, because the birthday height is one of the blocks that gets scanned, not the base block.

Non-blocking, the error in the output is minimal, and it isn't worth re-running CI.

_Originally posted by @str4d in https://github.com/zcash/librustzcash/pull/944#discussion_r1317659668_

**Comment by daira** [comment]
This only has a small effect on the progress measurement.

**Comment by nuttycom** [comment]
Fixed by #1564
