### ISSUE TITLE
[CI] Code coverage step is broken

### ISSUE THREAD

**Issue by daira** [zcash/librustzcash#967]
https://github.com/zcash/librustzcash/actions/runs/6153343984/job/16697065227?pr=908
![Partial screenshot showing an error from `cargo tarpaulin` at the code coverage step of PR #908.](https://github.com/zcash/librustzcash/assets/643204/f32aca53-58c2-4612-8435-a58b15ee1245)

**Comment by nuttycom** [comment]
This was fixed a while ago.
