### ISSUE TITLE
Document that `WalletRead::suggest_scan_ranges` returns ranges in descending priority order

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#971]
It isn't mentioned there:
https://github.com/zcash/librustzcash/blob/1e39daf6f83c4b62d645e74385d24299dc4414c7/zcash_client_backend/src/data_api.rs#L253-L263

but that's how we implemented it, and the current downstream consumers all assume that's what happens, due to this comment in the `zcash_client_backend::data_api::chain` module documentation:

https://github.com/zcash/librustzcash/blob/1e39daf6f83c4b62d645e74385d24299dc4414c7/zcash_client_backend/src/data_api/chain.rs#L58-L60

**Comment by nuttycom** [comment]
Fixed in #979
