### ISSUE TITLE
Enable UTXOs spent in expired shielding transactions to be spendable

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#986]
Currently `zcash_client_sqlite` assumes that once a UTXO is shielded, it never needs to be spendable again. However, shielding transactions are created with an expiry height the same as any other transaction, so we need to handle this in some way.

The trickiest part is likely to be how we handle two competing chain tips where a shielding transaction is mined on one chain, and expired on the other.

Opened from https://github.com/zcash/librustzcash/pull/985#discussion_r1333774156.

**Comment by str4d** [comment]
The fourth commit of #1402 changes the transparent logic for balance calculation and selection to be the same as shielded. I'm not confident that we don't still have a problem here; I think we will continue to have risk here until transparent scanning is closer to shielded scanning.

**Comment by nuttycom** [comment]
Between #1402, #1473 and #1496 we now believe this to be resolved.
