### ISSUE TITLE
Nullifier as public input is inconsistent between protocol and implementation

### ISSUE THREAD

**Issue by skipjackcn** [zcash/librustzcash#99]
In the protocol specification, when verifying proof, nullifier is split into 2 parts as follows.
<img width="834" alt="nf" src="https://user-images.githubusercontent.com/50454638/62930488-1ba2d380-bdef-11e9-8a80-03b4a2d5902b.png">

In _check_spend_ function, 
https://github.com/zcash/librustzcash/blob/4255b44b218837bc52d01f32caf609e6eaa6a8a2/zcash_proofs/src/sapling/verifier.rs#L93-L102
and _compute_multipacking_ function, 
https://github.com/zcash/librustzcash/blob/4255b44b218837bc52d01f32caf609e6eaa6a8a2/sapling-crypto/src/circuit/multipack.rs#L56-L79

E::Fr::CAPACITY is 254 rather than 251. It means nf_{0..253}^{old} and nf_{254,255}^{old} are used in public_input[5] and public_input[6], respectively. In fact, it is reasonable that CAPACITY is 254, since the rs is 255-bit.

**Comment by str4d** [comment]
Good spot! This looks like a spec bug; we certainly aren't going to alter how the nullifier is packed in the circuit now 😄

I've opened https://github.com/zcash/zips/issues/264 for tracking this.

**Comment by daira** [comment]
This will be fixed in 2019.0.5.
