### ISSUE TITLE
Move Sapling proving and verifying code from `zcash_proofs` to `zcash_primitives::sapling`

### ISSUE THREAD

**Issue by str4d** [zcash/librustzcash#998]
As part of the effort to recreate the `sapling-crypto` crate, we should move its proving and verifying code back alongside the rest of the Sapling protocol.

The original design of a separate `zcash_proofs` crate was motivated by enabling downstream users to offload proving to a trusted remote server that could be more powerful (and run for shorter periods of time than the longer-lived and lower-power transaction building servers). In practice no one has used this functionality, and the `orchard` crate does not follow the same pattern. However, similar logic _is_ possible due to how the `orchard` builder is structured: it produces a `Bundle<InProgress<Unproven, Unsigned>, V>` that can then be independently proven or signed via type system state transitions. If desired, one of these transitions could be "serialize the unproven state, send it to a remote prover, and get back the proof".

We should therefore simplify the Sapling proof building logic to be more similar to how Orchard operates, and move it into `zcash_primitives::sapling`. This issue's move is not expected to be directly released to users, but instead be an intermediate step in a feature branch that culminates in the introduction of `sapling-crypto` as a dependency.

**Comment by daira** [comment]
This appears to have been fixed by #999 and #1001.
